// The error code 5 prevention entry. Comment out or uncomment as necessary
// const int COMPILER_BREAKS_ON_ME_OR_NOT = 0xffffffff;


//missing bioware ones
//const int FEAT_EPIC_PLANAR_TURNING = 854;

// skill based feats
const int FEAT_JUMP = 2884;

// Racial Feats
const int FEAT_WEMIC_JUMP_8        = 4518;
const int FEAT_URDINNIR_STONESKIN  = 4644;
const int FEAT_AVARIEL_DIVE        = 4645;
const int FEAT_AYUAN_FEAR          = 4646;
const int FEAT_AYUAN_ENTANGLE      = 4647;
const int FEAT_AYUAN_DARKNESS      = 4648;
const int FEAT_AYUAN_NEUTRALIZE_POISON  = 4649;
//const int FEAT_AASIMAR_LIGHT       = 4650;
const int FEAT_TIEFLING_DARK       = 4651;
const int FEAT_SVIRF_BLIND_DEAF         = 4652;
const int FEAT_SVIRF_BLUR          = 4653;
const int FEAT_SVIRF_DISGUISE      = 4654;
const int FEAT_SVIRF_REVERT        = 4655;
const int FEAT_RAK_DISGUISE        = 4656;
const int FEAT_RAK_REVERT          = 4657;
const int FEAT_PYUAN_CHARM         = 4658;
const int FEAT_PYUAN_DARKNESS      = 4659;
const int FEAT_PYUAN_ENTANGLE      = 4660;
const int FEAT_PYUAN_FEAR          = 4661;
const int FEAT_PIXIE_INVIS         = 4662;
const int FEAT_PIXIE_CONFUSE       = 4663;
const int FEAT_PIXIE_ENTANGLE      = 4664;
const int FEAT_PIXIE_DISPEL_MAGIC  = 4665;
const int FEAT_PIXIE_POLYMORPH          = 4666;
const int FEAT_PIXIE_REVERT        = 4667;
const int FEAT_MINOTAUR_CHARGE          = 4668;
const int FEAT_ILLITHID_CHARM      = 4669;
const int FEAT_ILLITHID_BLAST      = 4670;
const int FEAT_ILLITHID_SUCKBRAIN  = 4671;
const int FEAT_GITHZERAI_DAZE      = 4672;
const int FEAT_GITHYANKI_DAZE      = 4673;
const int FEAT_GITHYANKI_BLUR      = 4674;
const int FEAT_FEYRI_CHARMPERSON   = 4675;
const int FEAT_FEYRI_CLAIRAUDIENCE = 4676;
const int FEAT_FEYRI_DARKNESS      = 4677;
const int FEAT_FEYRI_ENERVATION         = 4678;
const int FEAT_FEYRI_ALTER         = 4679;
const int FEAT_FEYRI_REVERT        = 4680;
const int FEAT_DUERGAR_INVIS       = 4681;
//const int FEAT_DROW_DARKNESS       = 4682;
//const int FEAT_DROW_FAERIE_FIRE         = 4683;

const int FEAT_LTSENSE = 4700;
const int FEAT_LTBLIND = 4701;

const int FEAT_SPELL5  = 4702;
const int FEAT_SPELL10 = 4420;
const int FEAT_SPELL11 = 4703;
const int FEAT_SPELL13 = 4704;
const int FEAT_SPELL14 = 4705;
const int FEAT_SPELL15 = 4706;
const int FEAT_SPELL18 = 4707;
const int FEAT_SPELL25 = 4708;
const int FEAT_SPELL27 = 4709;

const int FEAT_DWARVEN    = 4710;
const int FEAT_ELVEN      = 4711;
const int FEAT_GNOMISH    = 4712;
const int FEAT_HALFLING   = 4713;
const int FEAT_ORCISH     = 4714;
const int FEAT_HUMAN      = 4715;
const int FEAT_OUTSIDER   = 4716;
const int FEAT_GIANT      = 4717;
const int FEAT_FEY        = 4718;
const int FEAT_GOBLINOID  = 4719;
const int FEAT_MONSTEROUS = 4720;
const int FEAT_REPTILIAN  = 4721;
const int FEAT_ABERRATION = 4722;
const int FEAT_ELEMENTAL  = 4759;
const int FEAT_UNDEAD      = 4769;
const int FEAT_BEAST       = 4770;
const int FEAT_VERMIN      = 4771;
//const int FEAT_DRAGON      = 4773;

const int FEAT_HARD_AIR   = 4723;
const int FEAT_HARD_EARTH = 4724;
const int FEAT_HARD_FIRE  = 4725;
const int FEAT_HARD_WATER = 4726;
const int FEAT_HARD_ELEC  = 4727;
const int FEAT_POISON_3   = 4728;
const int FEAT_POISON_4   = 4768;

const int FEAT_IMM_COLD     = 4729;
const int FEAT_IMM_PHANT    = 4730;
const int FEAT_NONDETECTION = 4731;
const int FEAT_IMM_APOI     = 4732;

const int FEAT_NATARM_1     = 4733;
const int FEAT_NATARM_2     = 4761;
const int FEAT_NATARM_3     = 4734;
const int FEAT_NATARM_4     = 4735;
const int FEAT_NATARM_5     = 4736;
const int FEAT_NATARM_6     = 4737;
const int FEAT_NATARM_7     = 4764;
const int FEAT_NATARM_8     = 4765;
const int FEAT_NATARM_9     = 4738;
const int FEAT_NATARM_10    = 4766;

const int FEAT_BREATHLESS   = 4739;
const int FEAT_CONSTRICT    = 4740;
const int FEAT_REGEN5       = 4741;
const int FEAT_REND         = 4742;
const int FEAT_RESIST_FIRE5 = 4743;
const int FEAT_SUFFOCATION  = 4744;
const int FEAT_VERYHEROIC   = 4745;
const int FEAT_VULN_COLD    = 4746;
const int FEAT_DAM_RED10    = 4747;
const int FEAT_DAM_RED15    = 4748;

const int FEAT_SA_HIDE      = 4767;
const int FEAT_SA_HIDEU     = 4749;
const int FEAT_SA_HIDEF     = 4750;
const int FEAT_SA_MOVE4     = 4751;
const int FEAT_SA_JUMP      = 4752;
const int FEAT_SA_BLUFF     = 4753;
const int FEAT_SA_HIDE4      = 4754;
const int FEAT_SA_CRFTARM   = 4757;
const int FEAT_SA_CRFTWEAP  = 4758;
const int FEAT_SA_CRFTTRAP  = 4517;
const int FEAT_SA_SPOT_4    = 4762;
const int FEAT_SA_JUMP_4    = 4763;
const int FEAT_LEAP     = 4772;
const int FEAT_KEEN_SIGHT   = 4774;
const int FEAT_SA_APPRAISE  = 4792;

const int FEAT_ALTFORM                  = 4754;
const int FEAT_DISGUISE                 = 4755;
const int FEAT_LARGE                    = 4760;
const int FEAT_AZER_HEAT      = 4790;
//const int FEAT_SVIRFNEBLIN_DODGE        = 4791;
const int FEAT_WATER_BREATHING          = 4793;
const int FEAT_MINOT_SCENT         = 4795;

const int FEAT_CHAMELEON      = 4576;
const int FEAT_BONUS_RIVER         = 4577;
const int FEAT_BONUS_BAMBOO        = 4578;
const int FEAT_BONUS_SEA      = 4579;
const int FEAT_BONUS_MIND_2        = 4580;
const int FEAT_SA_LISTEN_4         = 4581;
const int FEAT_SA_SEARCH_4         = 4582;
const int FEAT_FREEMOVEMENT        = 4583;
const int FEAT_TIRELESS            = 4584;
const int FEAT_SUBDUAL             = 4585;
const int FEAT_SENSITIVESMELL      = 4586;
const int FEAT_REGEN2              = 4587;
const int FEAT_POORHEARING         = 4588;
const int FEAT_MINUS_PERSUADE_2         = 4589;
const int FEAT_ACUTEHEARING        = 4590;
const int FEAT_COMPOSITEPLATING         = 4591;
const int FEAT_DAYLIGHTADAPT       = 4592;
const int FEAT_BONUS_FEAR_2        = 4593;
const int FEAT_LACKOFFOCUS         = 4594;
const int FEAT_PSA_LORESPELL       = 4595;
const int FEAT_SA_PERFORM_4        = 4596;
const int FEAT_PSA_PERSUADE        = 4597;
const int FEAT_RESTRICT_BOOTS      = 4598;
const int FEAT_RESTRICT_SHIELD          = 4599;
const int FEAT_TINY           = 4614;
const int FEAT_SPELL8              = 4615;
const int FEAT_SPELL16             = 4616;
const int FEAT_SPELL17             = 4617;
const int FEAT_SPELL19             = 4619;
const int FEAT_SPELL20             = 4620;
const int FEAT_SPELL21             = 4621;
const int FEAT_SPELL22             = 4622;
const int FEAT_SPELL23             = 4623;
const int FEAT_NATARM_11      = 4624;
const int FEAT_NATARM_12      = 4625;
const int FEAT_NATARM_13      = 4626;
const int FEAT_NATARM_14      = 4627;
const int FEAT_NATARM_15      = 4628;
const int FEAT_NATARM_16      = 4629;
const int FEAT_NATARM_17      = 4630;
const int FEAT_NATARM_18      = 4631;
const int FEAT_NATARM_19      = 4632;
const int FEAT_NATARM_20      = 4633;
const int FEAT_NATARM_21      = 4634;
const int FEAT_NATARM_22      = 4635;
const int FEAT_LIFEPATH            = 4636;
const int FEAT_CRAFTGUILD          = 4637;
const int FEAT_TECHGUILD      = 4638;
const int FEAT_SAGEGUILD      = 4639;
const int FEAT_VOWOFSILENCE        = 4640;
const int FEAT_COLDTOPOR      = 4641;
const int FEAT_COWARDPITY          = 4642;
const int FEAT_IMMUNE_PETRIFICATION     = 4643;
const int FEAT_BONUS_COLD_2        = 4684;
const int FEAT_BONUS_FIRE_2        = 4685;
const int FEAT_BONUS_SONIC_4       = 4686;
const int FEAT_BONUS_PSIONICS_4         = 4687;
const int FEAT_SA_HEAL             = 4755;
const int FEAT_SA_PERFORM          = 4756;
const int FEAT_THRIKREEN_LEAP      = 4775;
const int FEAT_BIRDSEYE            = 4776;
const int FEAT_SA_ANIMAL_EMP       = 4777;
const int FEAT_SA_ANIMAL_EMP_6          = 4778;
const int FEAT_KENDERBLUFF         = 4779;
const int FEAT_CLAUSTROPHOBIC      = 4780;
const int FEAT_RESTRICT_ARMOR      = 4781;
const int FEAT_IMMUNE_ACID         = 4782;
const int FEAT_IMMUNE_CHARM        = 4783;
const int FEAT_IMMUNE_CONFUSION         = 4784;
const int FEAT_IMMUNE_DISEASE           = 4785;
const int FEAT_IMMUNE_ELECTRICITY  = 4786;
const int FEAT_VULN_FIRE      = 4787;
const int FEAT_VULN_GAS            = 4788;
const int FEAT_FROSTYTOUCH         = 4789;
const int FEAT_SA_OPEN             = 4794;
const int FEAT_NATPSIONIC_1        = 4796;
const int FEAT_NATPSIONIC_2        = 4797;
const int FEAT_NATPSIONIC_3        = 4798;
const int FEAT_HUGE           = 4799;
const int FEAT_SMALL          = 375;

//Passive Feats
const int FEAT_ETERNAL_FREEDOM                         = 4298;
const int FEAT_INTUITIVE_ATTACK                        = 3166;
const int FEAT_RAVAGEGOLDENICE                         = 3162;
const int FEAT_DRAGONSONG                              = 3440;
const int FEAT_UNDEAD_MASTERY                          = 3446;
const int FEAT_IMPROVED_FAVORED_ENEMY                  = 3454;
const int FEAT_FAVORED_POWER_ATTACK                    = 3455;
const int FEAT_EXTENDED_RAGE                           = 3456;
const int FEAT_DARKNESS_DOMAIN                         = 3458;

const int FEAT_FOCUSED_SPELL_PENETRATION_ABJURATION    = 3128;
const int FEAT_FOCUSED_SPELL_PENETRATION_CONJURATION   = 3129;
const int FEAT_FOCUSED_SPELL_PENETRATION_DIVINATION    = 3130;
const int FEAT_FOCUSED_SPELL_PENETRATION_ENCHATMENT    = 3131;
const int FEAT_FOCUSED_SPELL_PENETRATION_EVOCATION     = 3132;
const int FEAT_FOCUSED_SPELL_PENETRATION_ILLUSION      = 3133;
const int FEAT_FOCUSED_SPELL_PENETRATION_NECROMANCY    = 3134;
const int FEAT_FOCUSED_SPELL_PENETRATION_TRANSMUTATION = 3135;
const int FEAT_DISCIPLE_OF_SUN                 = 3127;
const int FEAT_PRACTISED_SPELLCASTER_BARD              = 3121;
const int FEAT_PRACTISED_SPELLCASTER_CLERIC            = 3122;
const int FEAT_PRACTISED_SPELLCASTER_DRUID             = 3123;
const int FEAT_PRACTISED_SPELLCASTER_SORCERER          = 3124;
const int FEAT_PRACTISED_SPELLCASTER_WIZARD            = 3125;

//const int FEAT_EPIC_DIVINE_MIGHT                       = 3120;
const int FEAT_EPIC_DIVINE_RESISTANCE                  = 3119;
const int FEAT_EPIC_DIVINE_SHIELD                      = 3548;
const int FEAT_DIVINE_CLEANSING                        = 3118;
//const int FEAT_DIVINE_RESISTANCE                       = 3117;
const int FEAT_DIVINE_VIGOR                            = 3116;
const int FEAT_EPIC_DIVINE_VIGOR                       = 3115;
const int FEAT_INVOKE_DIVINE_WRATH                     = 3114;
const int FEAT_SHADOWWEAVE                             = 2960;
const int FEAT_TENACIOUSMAGIC                          = 2961;
const int FEAT_PERNICIOUSMAGIC                         = 2962;
const int FEAT_INSIDIOUSMAGIC                          = 2963;
const int FEAT_UNHOLY_STRIKE                           = 3451;

const int FEAT_EPIC_LEADERSHIP                         = 4366;
const int FEAT_LEGENDARY_COMMANDER                     = 4367;

const int FEAT_TWO_WEAPON_REND                         = 3113;

// Libris Mortis
const int FEAT_REQUIEM                                 = 6555;

// Magic of Faerun
const int FEAT_SPELL_GIRDING                           = 6556;

// Complete Adventurer
const int FEAT_FORCE_PERSONALITY                       = 6557;
const int FEAT_INSIGHTFUL_REFLEXES                     = 6558;
const int FEAT_TACTILE_TRAPSMITH                       = 6559;

// Complete Divine
//const int FEAT_AUGMENT_HEALING                         = 6560;

//Corpsecrafter
const int FEAT_CORPSECRAFTER                           = 4014;
const int FEAT_BOLSTER_RESISTANCE                      = 4015;
const int FEAT_DEADLY_CHILL                            = 4016;
const int FEAT_DESTRUCTION_RETRIBUTION                 = 4017;
const int FEAT_HARDENED_FLESH                          = 4018;
const int FEAT_NIMBLE_BONES                            = 4019;

// Forgotten Realms Campaign Setting
const int FEAT_INSCRIBE_RUNE                           = 6562;

// Bonus Domains
const int FEAT_BONUS_DOMAIN_AIR                  = 6101;
const int FEAT_BONUS_DOMAIN_ANIMAL               = 6102;
const int FEAT_BONUS_DOMAIN_DEATH                = 6103;
const int FEAT_BONUS_DOMAIN_DESTRUCTION          = 6104;
const int FEAT_BONUS_DOMAIN_EARTH                = 6105;
const int FEAT_BONUS_DOMAIN_EVIL                 = 6106;
const int FEAT_BONUS_DOMAIN_FIRE                 = 6107;
const int FEAT_BONUS_DOMAIN_GOOD                 = 6108;
const int FEAT_BONUS_DOMAIN_HEALING              = 6109;
const int FEAT_BONUS_DOMAIN_KNOWLEDGE            = 6110;
const int FEAT_BONUS_DOMAIN_MAGIC                = 6111;
const int FEAT_BONUS_DOMAIN_PLANT                = 6112;
const int FEAT_BONUS_DOMAIN_PROTECTION           = 6113;
const int FEAT_BONUS_DOMAIN_STRENGTH             = 6114;
const int FEAT_BONUS_DOMAIN_SUN                  = 6115;
const int FEAT_BONUS_DOMAIN_TRAVEL               = 6116;
const int FEAT_BONUS_DOMAIN_TRICKERY             = 6117;
const int FEAT_BONUS_DOMAIN_WAR                  = 6118;
const int FEAT_BONUS_DOMAIN_WATER                = 6119;
const int FEAT_BONUS_DOMAIN_DARKNESS             = 6120;
const int FEAT_BONUS_DOMAIN_STORM                = 6121;
const int FEAT_BONUS_DOMAIN_METAL                = 6122;
const int FEAT_BONUS_DOMAIN_PORTAL               = 6123;
const int FEAT_BONUS_DOMAIN_FORCE                = 6124;
const int FEAT_BONUS_DOMAIN_SLIME                = 6125;
const int FEAT_BONUS_DOMAIN_TYRANNY              = 6126;
const int FEAT_BONUS_DOMAIN_DOMINATION           = 6127;
const int FEAT_BONUS_DOMAIN_SPIDER               = 6128;
const int FEAT_BONUS_DOMAIN_UNDEATH              = 6129;
const int FEAT_BONUS_DOMAIN_TIME                 = 6130;
const int FEAT_BONUS_DOMAIN_DWARF                = 6131;
const int FEAT_BONUS_DOMAIN_CHARM                = 6132;
const int FEAT_BONUS_DOMAIN_ELF                  = 6133;
const int FEAT_BONUS_DOMAIN_FAMILY               = 6134;
const int FEAT_BONUS_DOMAIN_FATE                 = 6135;
const int FEAT_BONUS_DOMAIN_GNOME                = 6136;
const int FEAT_BONUS_DOMAIN_ILLUSION             = 6137;
const int FEAT_BONUS_DOMAIN_HATRED               = 6138;
const int FEAT_BONUS_DOMAIN_HALFLING             = 6139;
const int FEAT_BONUS_DOMAIN_NOBILITY             = 6140;
const int FEAT_BONUS_DOMAIN_OCEAN                = 6141;
const int FEAT_BONUS_DOMAIN_ORC                  = 6142;
const int FEAT_BONUS_DOMAIN_RENEWAL              = 6143;
const int FEAT_BONUS_DOMAIN_RETRIBUTION          = 6144;
const int FEAT_BONUS_DOMAIN_RUNE                 = 6145;
const int FEAT_BONUS_DOMAIN_SPELLS               = 6146;
const int FEAT_BONUS_DOMAIN_SCALEYKIND           = 6147;
const int FEAT_BONUS_DOMAIN_BLIGHTBRINGER        = 6148;

// Domain Power Feats
const int FEAT_DOMAIN_POWER_DARKNESS             = 3458;
const int FEAT_DOMAIN_POWER_STORM                = 4038;
const int FEAT_DOMAIN_POWER_METAL                = 4037;
const int FEAT_DOMAIN_POWER_PORTAL               = 4039;
const int FEAT_DOMAIN_POWER_FORCE                = 4042;
const int FEAT_DOMAIN_POWER_SLIME                = 4043;
const int FEAT_DOMAIN_POWER_TYRANNY              = 4062;
const int FEAT_DOMAIN_POWER_DOMINATION           = 4049;
const int FEAT_DOMAIN_POWER_SPIDER               = 4061;
const int FEAT_DOMAIN_POWER_UNDEATH              = 4050;
const int FEAT_DOMAIN_POWER_TIME                 = 4044;
const int FEAT_DOMAIN_POWER_DWARF                = 4040;
const int FEAT_DOMAIN_POWER_CHARM                = 4045;
const int FEAT_DOMAIN_POWER_ELF                  = 4059;
const int FEAT_DOMAIN_POWER_FAMILY               = 4051;
const int FEAT_DOMAIN_POWER_FATE                 = 4048;
const int FEAT_DOMAIN_POWER_GNOME                = 4058;
const int FEAT_DOMAIN_POWER_ILLUSION             = 4053;
const int FEAT_DOMAIN_POWER_HATRED               = 4054;
const int FEAT_DOMAIN_POWER_HALFLING             = 4052;
const int FEAT_DOMAIN_POWER_NOBILITY             = 4055;
const int FEAT_DOMAIN_POWER_OCEAN                = 4063;
const int FEAT_DOMAIN_POWER_ORC                  = 4041;
const int FEAT_DOMAIN_POWER_RENEWAL              = 4060;
const int FEAT_DOMAIN_POWER_RETRIBUTION          = 4056;
const int FEAT_DOMAIN_POWER_RUNE                 = 4047;
const int FEAT_DOMAIN_POWER_SPELLS               = 4046;
const int FEAT_DOMAIN_POWER_SCALEYKIND           = 4057;
const int FEAT_DOMAIN_POWER_BLIGHTBRINGER        = 2250;

// Cast Bonus Domain
const int FEAT_CAST_DOMAIN_LEVEL_ONE             = 6149;
const int FEAT_CAST_DOMAIN_LEVEL_TWO             = 6150;
const int FEAT_CAST_DOMAIN_LEVEL_THREE               = 6151;
const int FEAT_CAST_DOMAIN_LEVEL_FOUR            = 6152;
const int FEAT_CAST_DOMAIN_LEVEL_FIVE                = 6153;
const int FEAT_CAST_DOMAIN_LEVEL_SIX                 = 6154;
const int FEAT_CAST_DOMAIN_LEVEL_SEVEN               = 6155;
const int FEAT_CAST_DOMAIN_LEVEL_EIGHT               = 6156;
const int FEAT_CAST_DOMAIN_LEVEL_NINE                = 6157;

const int FEAT_CHECK_DOMAIN_SLOTS            = 6100;

//Vile
const int FEAT_VILE_MARTIAL_CLUB          = 3357;
const int FEAT_VILE_MARTIAL_DAGGER        = 3358;
const int FEAT_VILE_MARTIAL_MACE          = 3359;
const int FEAT_VILE_MARTIAL_MORNINGSTAR   = 3360;
const int FEAT_VILE_MARTIAL_QUATERSTAFF   = 3361;
const int FEAT_VILE_MARTIAL_SPEAR         = 3362;
const int FEAT_VILE_MARTIAL_SHORTSWORD    = 3363;
const int FEAT_VILE_MARTIAL_RAPIER        = 3364;
const int FEAT_VILE_MARTIAL_SCIMITAR      = 3365;
const int FEAT_VILE_MARTIAL_LONGSWORD     = 3366;
const int FEAT_VILE_MARTIAL_GREATSWORD    = 3367;
const int FEAT_VILE_MARTIAL_HANDAXE       = 3368;
const int FEAT_VILE_MARTIAL_BATTLEAXE     = 3369;
const int FEAT_VILE_MARTIAL_GREATAXE      = 3370;
const int FEAT_VILE_MARTIAL_HALBERD       = 3371;
const int FEAT_VILE_MARTIAL_LIGHTHAMMER   = 3372;
const int FEAT_VILE_MARTIAL_LIGHTFLAIL    = 3373;
const int FEAT_VILE_MARTIAL_WARHAMMER     = 3374;
const int FEAT_VILE_MARTIAL_HEAVYFLAIL    = 3375;
const int FEAT_VILE_MARTIAL_SCYTHE        = 3376;
const int FEAT_VILE_MARTIAL_KATANA        = 3377;
const int FEAT_VILE_MARTIAL_BASTARDSWORD  = 3378;
const int FEAT_VILE_MARTIAL_DIREMACE      = 3379;
const int FEAT_VILE_MARTIAL_DOUBLEAXE     = 3380;
const int FEAT_VILE_MARTIAL_TWOBLADED     = 3381;
const int FEAT_VILE_MARTIAL_KAMA          = 3382;
const int FEAT_VILE_MARTIAL_KUKRI         = 3383;
const int FEAT_VILE_MARTIAL_HEAVYCROSSBOW = 3384;
const int FEAT_VILE_MARTIAL_LIGHTCROSSBOW = 3385;
const int FEAT_VILE_MARTIAL_SLING         = 3386;
const int FEAT_VILE_MARTIAL_LONGBOW       = 3387;
const int FEAT_VILE_MARTIAL_SHORTBOW      = 3396;
const int FEAT_VILE_MARTIAL_SHURIKEN      = 3397;
const int FEAT_VILE_MARTIAL_DART          = 3398;
const int FEAT_VILE_MARTIAL_SICKLE        = 3399;
const int FEAT_VILE_MARTIAL_DWAXE         = 3452;
const int FEAT_VILE_MARTIAL_MINDBLADE     = 3624;

// Weapon Focus (Ray)
const int FEAT_WEAPON_FOCUS_RAY           = 4819;
const int FEAT_EPIC_WEAPON_FOCUS_RAY      = 4820;

// Battleguard Tempus
const int TEMPUS_ABILITY_ENHANC1   = 1;
const int TEMPUS_ABILITY_ENHANC2   = 2;
const int TEMPUS_ABILITY_ENHANC3   = 3;
const int TEMPUS_ABILITY_FIRE1D6   = 4;
const int TEMPUS_ABILITY_COLD1D6   = 5;
const int TEMPUS_ABILITY_ELEC1D6   = 6;
const int TEMPUS_ABILITY_KEEN      = 7;
const int TEMPUS_ABILITY_ANARCHIC  = 8;
const int TEMPUS_ABILITY_AXIOMATIC = 9;
const int TEMPUS_ABILITY_HOLY      = 10;
const int TEMPUS_ABILITY_UNHOLY    = 11;
const int TEMPUS_ABILITY_VICIOUS   = 12;
const int TEMPUS_ABILITY_DISRUPTION= 13;
const int TEMPUS_ABILITY_WOUNDING  = 14;
const int TEMPUS_ABILITY_BARSKIN   = 15;
const int TEMPUS_ABILITY_CONECOLD  = 16;
const int TEMPUS_ABILITY_DARKNESS  = 17;
const int TEMPUS_ABILITY_FIREBALL  = 18;
const int TEMPUS_ABILITY_HASTE     = 19;
const int TEMPUS_ABILITY_IMPROVINV = 20;
const int TEMPUS_ABILITY_LIGHTBOLT = 21;
const int TEMPUS_ABILITY_MAGICMISSILE  = 22;
const int TEMPUS_ABILITY_WEB       = 23;
const int TEMPUS_ABILITY_VAMPIRE   = 24;

// Polymorph
const int POLY_SHAPEDRAGONGOLD  = 130;
const int POLY_SHAPEDRAGONRED   = 131;
const int POLY_SHAPEDRAGONPRYS  = 132;


//Active Feats
const int FEAT_FIST_OF_IRON               = 3145;
const int FEAT_POWER_ATTACK_SINGLE_RADIAL = 3143;
const int FEAT_POWER_ATTACK_FIVES_RADIAL  = 3144;
const int FEAT_POWER_ATTACK_QUICKS_RADIAL = 3179;
const int FEAT_TELEPORT_MANAGEMENT_RADIAL = 4235;
const int FEAT_ZONE_OF_ANIMATION          = 2891;

// Werewolf Template
const int FEAT_PRESTIGE_WOLF_FORM                  = 3518;
const int FEAT_PRESTIGE_WEREWOLF_FORM              = 3519;
const int FEAT_TRUE_LYCANTHROPE                    = 3520;
const int FEAT_PRESTIGE_WOLF_EMPATHY               = 3521;
const int FEAT_PRESTIGE_WOLFCLASS_1                = 3522;
const int FEAT_PRESTIGE_WOLFCLASS_2                = 3523;
const int FEAT_PRESTIGE_WEREWOLFCLASS_1            = 3524;
const int FEAT_PRESTIGE_WEREWOLFCLASS_2            = 3525;
const int FEAT_PRESTIGE_WEREWOLFCLASS_3            = 3526;
const int FEAT_PRESTIGE_LYCANTHROPE                = 3527;

// Arcane Duelist
const int FEAT_AD_CHOSEN_WEAPON                    = 3530;
const int FEAT_AD_ENCHANT_CHOSEN_WEAPON            = 3531;
const int FEAT_AD_APPARENT_DEFENSE                 = 3532;
const int FEAT_AD_DEX_ATTACK                       = 3533;
const int FEAT_AD_FLURRY_OF_SWORDS                 = 3534;
const int FEAT_AD_FALSE_KEENNESS                   = 3535;
const int FEAT_AD_BLUR                             = 3536;
const int FEAT_AD_MISLEAD                          = 3537;

//Drow Judicator Feats
const int FEAT_COMMAND_SPIDERS     = 6542;
const int FEAT_WAR_STRIKE          = 6543;
const int FEAT_SELVETARMS_BLESSING = 6547;
const int FEAT_LOLTHS_MEAT         = 6541;

//Ranger Feats
const int FEAT_RANGER_DUAL = 374;

//Exalted Feat
const int FEAT_SAC_VOW = 3388;
const int FEAT_VOW_OBED = 3389;
const int FEAT_EXALTED_TURNING = 3168;
const int FEAT_HAND_HEALER = 3167;
const int FEAT_NIMBUSLIGHT = 3165;
const int FEAT_HOLYRADIANCE = 3164;
const int FEAT_STIGMATA = 3163;
const int FEAT_SERVHEAVEN = 3355;
const int FEAT_RANGED_SMITE = 3356;

//Vile Feat
const int FEAT_LICHLOVED                               = 3395;
const int FEAT_THRALL_TO_DEMON                         = 6716;
const int FEAT_DISCIPLE_OF_DARKNESS                    = 4012;
const int FEAT_EB_HAND                                 = 3390;
const int FEAT_EB_HEAD                                 = 3391;
const int FEAT_EB_CHEST                                = 3392;
const int FEAT_EB_ARM                                  = 3393;
const int FEAT_EB_NECK                                 = 3394;
const int FEAT_VILE_DEFORM_OBESE               = 4406;
const int FEAT_VILE_DEFORM_GAUNT               = 4407;
const int FEAT_VILE_WILL_DEFORM                = 4408;

//archmage
const int FEAT_MASTERY_SHAPES = 3006;
const int FEAT_SPELL_POWER_I = 3007;
const int FEAT_SPELL_POWER_II = 3008;
const int FEAT_SPELL_POWER_III = 3009;
const int FEAT_SPELL_POWER_IV = 3010;
const int FEAT_SPELL_POWER_V = 3011;
const int FEAT_ARCANE_FIRE = 3012;
const int FEAT_SPELL_LIKE = 3013;

//Master Harper
const int FEAT_LYCANBANE = 6504 ;
const int FEAT_DENEIRS_OREL = 6508 ;
const int FEAT_MILILS_EAR = 6506 ;
const int FEAT_INSTRUMENT = 6509;
const int FEAT_MIELIKKI = 6505;

// Ghost-Faced Killer
const int FEAT_GFKILL_GHOST_STEP = 4490;
const int FEAT_GFKILL_GHOST_STEP2 = 4491;
const int FEAT_GFKILL_GHOST_STEP3 = 4492;
const int FEAT_GFKILL_GHOST_STEP4 = 4493;
const int FEAT_GFKILL_GHOST_STEP5 = 4494;
const int FEAT_GFKILL_GHOST_STEP6 = 4495;
const int FEAT_GFKILL_GHOST_STEP7 = 4496;
const int FEAT_GFKILL_GHOST_STEP8 = 4497;
const int FEAT_GFKILL_GHOST_STEP9 = 4498;
const int FEAT_GFKILL_GHOST_STEP10 = 4499;
const int FEAT_FRIGHTFUL_ATTACK = 4500;
const int FEAT_FRIGHTFUL_ATTACK2 = 4501;
const int FEAT_FRIGHTFUL_ATTACK3 = 4502;
const int FEAT_FRIGHTFUL_ATTACK4 = 4503;
const int FEAT_FRIGHTFUL_ATTACK5 = 4504;
const int FEAT_FRIGHTFUL_ATTACK6 = 4505;
const int FEAT_FRIGHTFUL_ATTACK7 = 4506;
const int FEAT_FRIGHTFUL_ATTACK8 = 4507;
const int FEAT_FRIGHTFUL_ATTACK9 = 4508;
const int FEAT_FRIGHTFUL_ATTACK20 = 4509;
const int FEAT_FRIGHTFUL_CLEAVE = 4510;

// Thayan Knight
const int FEAT_TK_HORROR_1                         = 6740;
const int FEAT_TK_HORROR_2                         = 6741;
const int FEAT_TK_ZULKIR_FAVOUR                    = 6742;
const int FEAT_TK_ZULKIR_DEFEND                    = 6743;
const int FEAT_TK_ZULKIR_CHAMP                     = 6744;
const int FEAT_TK_FINAL_STAND                      = 6745;

//oozemaster
const int FEAT_MIN_OOZY_TOUCH_BROWN = 3020;
const int FEAT_MIN_OOZY_TOUCH_GRAY = 3021;
const int FEAT_MIN_OOZY_TOUCH_OCHRE = 3022;
const int FEAT_MIN_OOZY_TOUCH_FUNGUS = 3023;
const int FEAT_INDISCERNIBLE_ANATOMY = 3033;
const int FEAT_CHARISMA_PENALITY = 3034;
const int FEAT_ONE_WITH_THE_OOZE = 3035;

//disciple mephisto
const int FEAT_HELLFIRE_GRASP = 4000;
const int FEAT_FIRE_ADEPT = 4001;
const int FEAT_FIRE_RESISTANCE_10 = 4002;
const int FEAT_FIRE_RESISTANCE_20 = 4007;
const int FEAT_IMP_SUMMON_HAMATULA = 4011;

//Mage Killer
const int FEAT_AUGMENT_SUMMON = 6610;
const int FEAT_MK_REF_1 = 6600;
const int FEAT_MK_REF_2 = 6601;
const int FEAT_MK_REF_3 = 6602;
const int FEAT_MK_REF_4 = 6603;
const int FEAT_MK_REF_5 = 6604;
const int FEAT_MK_FORT_1 = 6605;
const int FEAT_MK_FORT_2 = 6606;
const int FEAT_MK_FORT_3 = 6607;
const int FEAT_MK_FORT_4 = 6608;
const int FEAT_MK_FORT_5 = 6609;

//Epic Mage Killer
const int FEAT_MK_FORT_6      = 6747;
const int FEAT_MK_FORT_7      = 6748;
const int FEAT_MK_FORT_8      = 6749;
const int FEAT_MK_FORT_9      = 6750;
const int FEAT_MK_FORT_10     = 6751;
const int FEAT_MK_FORT_11     = 6752;
const int FEAT_MK_FORT_12     = 6753;
const int FEAT_MK_FORT_13     = 6754;
const int FEAT_MK_FORT_14     = 6755;
const int FEAT_MK_FORT_15     = 6756;
const int FEAT_MK_REF_6  = 6757;
const int FEAT_MK_REF_7  = 6758;
const int FEAT_MK_REF_8  = 6759;
const int FEAT_MK_REF_9  = 6760;
const int FEAT_MK_REF_10      = 6761;
const int FEAT_MK_REF_11      = 6762;
const int FEAT_MK_REF_12      = 6763;
const int FEAT_MK_REF_13      = 6764;
const int FEAT_MK_REF_14      = 6765;
const int FEAT_MK_REF_15      = 6766;

//Spellsword
const int FEAT_SPELLS_1 = 6612;
const int FEAT_SPELLS_2 = 6613;
const int FEAT_SPELLS_3 = 6614;
const int FEAT_SPELLS_4 = 6615;
const int FEAT_SPELLS_5 = 6616;
const int FEAT_CHANNEL_SPELL_1 = 4688;
const int FEAT_CHANNEL_SPELL_2 = 4689;
const int FEAT_CHANNEL_SPELL_3 = 4690;
const int FEAT_CHANNEL_SPELL_4 = 4691;
const int FEAT_CHANNEL_SPELL_5 = 4692;
const int FEAT_CHANNEL_SPELL_6 = 4693;
const int FEAT_CHANNEL_SPELL_7 = 4694;
const int FEAT_CHANNEL_SPELL_8 = 4695;
const int FEAT_CHANNEL_SPELL_9 = 4696;
const int FEAT_MULTIPLE_CHANNEL_SPELL_1 = 4697;
const int FEAT_MULTIPLE_CHANNEL_SPELL_2 = 4698;
const int FEAT_MULTIPLE_CHANNEL_SPELL_3 = 4699;

//Epic Spellsword
const int FEAT_SPELLS_6 = 6634;
const int FEAT_SPELLS_7 = 6635;
const int FEAT_SPELLS_8 = 6636;
const int FEAT_SPELLS_9 = 6637;
const int FEAT_SPELLS_10 = 6638;
const int FEAT_SPELLS_11 = 6639;
const int FEAT_SPELLS_12 = 6640;
const int FEAT_SPELLS_13 = 6641;
const int FEAT_SPELLS_14 = 6642;
const int FEAT_SPELLS_15 = 6643;

//Diabolist
const int FEAT_DIABOL_DIABOLISM_1  = 4236;
const int FEAT_DIABOL_DIABOLISM_2  = 4237;
const int FEAT_DIABOL_DIABOLISM_3  = 4238;
const int FEAT_DIABOL_VILEDIAB          = 4239;
const int FEAT_DIABOL_IMPFAM       = 4240;

//Red Wizard of Thay
const int FEAT_RW_RES_ABJ     = 4210;
const int FEAT_RW_RES_CON     = 4211;
const int FEAT_RW_RES_DIV     = 4212;
const int FEAT_RW_RES_ENC     = 4213;
const int FEAT_RW_RES_EVO     = 4214;
const int FEAT_RW_RES_ILL     = 4215;
const int FEAT_RW_RES_NEC     = 4216;
const int FEAT_RW_RES_TRS     = 4217;
const int FEAT_RW_TF_ABJ      = 4218;
const int FEAT_RW_TF_CON      = 4219;
const int FEAT_RW_TF_DIV      = 4220;
const int FEAT_RW_TF_ENC      = 4221;
const int FEAT_RW_TF_EVO      = 4222;
const int FEAT_RW_TF_ILL      = 4223;
const int FEAT_RW_TF_NEC      = 4224;
const int FEAT_RW_TF_TRS      = 4225;
const int FEAT_RW_SPOWER_1    = 4226;
const int FEAT_RW_SPOWER_2    = 4227;
const int FEAT_RW_SPOWER_3    = 4228;
const int FEAT_RW_SPOWER_4    = 4229;
const int FEAT_RW_SPOWER_5    = 4230;
const int FEAT_RW_SDEF_1      = 4231;
const int FEAT_RW_SDEF_2      = 4232;
const int FEAT_RW_SDEF_3      = 4233;
const int FEAT_RW_SDEF_4      = 4234;

//Acolyte of the Skin
const int FEAT_WEAR_FIEND = 6617;
const int FEAT_FLAME_RESISTANT = 6618;
const int FEAT_FIENDISH_GLARE = 6619;
const int FEAT_SKIN_ADAPTION = 6621;
const int FEAT_COLD_RESISTANT = 6622;
const int FEAT_PIT_GLARE = 6623;
const int FEAT_SUMMON_FIEND = 6625;
const int FEAT_SYMBIOSIS = 6626;
const int FEAT_EPIC_SYMBIOSIS_1 = 6644; //here and below: epic
const int FEAT_EPIC_SYMBIOSIS_2 = 6645;
const int FEAT_EPIC_SYMBIOSIS_3 = 6646;
const int FEAT_EPIC_SYMBIOSIS_4 = 6647;
const int FEAT_EPIC_CON_1 = 6627;
const int FEAT_EPIC_CON_2 = 6628;
const int FEAT_EPIC_CON_3 = 6629;
const int FEAT_EPIC_INT_1 = 6632;
const int FEAT_EPIC_INT_2 = 6633;
const int FEAT_ACID_RESISTANT = 6630;
const int FEAT_ELEC_RESISTANT = 6631;

//Elemental Savant
const int FEAT_ES_TRANS_1 = 6650;
const int FEAT_ES_TRANS_2 = 6651;
const int FEAT_ES_TRANS_3 = 6652;
const int FEAT_ES_RESIST_1 = 6653;
const int FEAT_ES_RESIST_2 = 6654;
const int FEAT_ES_RESIST_3 = 6655;
const int FEAT_ES_FOCUS_1 = 6656;
const int FEAT_ES_FOCUS_2 = 6657;
const int FEAT_ES_FOCUS_3 = 6658;
const int FEAT_ES_PEN_1 = 6659;
const int FEAT_ES_PEN_2 = 6660;
const int FEAT_ES_PEN_3 = 6661;
const int FEAT_ES_PERFECTION = 6662;
const int FEAT_ES_FIRE = 6663;
const int FEAT_ES_COLD = 6664;
const int FEAT_ES_ELEC = 6665;
const int FEAT_ES_ACID = 6666;

//Epic Elemental Savant

const int FEAT_ES_FOCUS_4     = 6700;
const int FEAT_ES_FOCUS_5     = 6701;
const int FEAT_ES_FOCUS_6     = 6702;
const int FEAT_ES_FOCUS_7     = 6703;
const int FEAT_ES_FOCUS_8          = 6704;
const int FEAT_ES_FOCUS_9          = 6705;
const int FEAT_ES_FOCUS_10         = 6706;
const int FEAT_ES_PEN_4  = 6707;
const int FEAT_ES_PEN_5  = 6708;
const int FEAT_ES_PEN_6  = 6709;
const int FEAT_ES_PEN_7  = 6710;
const int FEAT_ES_PEN_8  = 6711;
const int FEAT_ES_PEN_9  = 6712;
const int FEAT_ES_PEN_10      = 6713;

//Duelist
//const int FEAT_CANNY_DEFENSE        = 6900;
const int FEAT_PRECISE_STRIKE_1D4   = 6901;
const int FEAT_PRECISE_STRIKE_2D4   = 6902;
const int FEAT_PRECISE_STRIKE_3D4   = 6923;
const int FEAT_PRECISE_STRIKE_4D4   = 6981;
const int FEAT_PRECISE_STRIKE_5D4   = 6982;
const int FEAT_PRECISE_STRIKE_6D4   = 6983;
const int FEAT_GRACE_2              = 6903;
const int FEAT_GRACE_4              = 6904;
const int FEAT_GRACE_6              = 6905;
const int FEAT_GRACE_8              = 6906;
const int FEAT_GRACE_10             = 6907;
const int FEAT_ACROBATIC_ATTACK_2   = 6908;
const int FEAT_ACROBATIC_ATTACK_4   = 6909;
const int FEAT_ACROBATIC_ATTACK_6   = 6910;
const int FEAT_ACROBATIC_ATTACK_8   = 6911;
//const int FEAT_ELABORATE_PARRY      = 6912;
const int FEAT_EPIC_DUELIST         = 6913;

//Hierophant
const int FEAT_BLAST_INFIDEL        = 6914;
const int FEAT_FAITH_HEALING        = 6915;
const int FEAT_MASTER_OF_ENERGY     = 6916;
const int FEAT_SPELLPOWER_2         = 6917;
const int FEAT_SPELLPOWER_4         = 6918;
const int FEAT_SPELLPOWER_6         = 6919;
const int FEAT_SPELLPOWER_8         = 6920;
const int FEAT_SPELLPOWER_10        = 6921;
const int FEAT_SPELL_LIKE_ABILITY_1 = 6925;
const int FEAT_SPELL_LIKE_ABILITY_2 = 6926;
const int FEAT_SPELL_LIKE_ABILITY_3 = 6927;
const int FEAT_SPELL_LIKE_ABILITY_4 = 6928;
const int FEAT_SPELL_LIKE_ABILITY_5 = 6929;

//Red Avenger
const int FEAT_FREE_KI_2            = 6850;
const int FEAT_FREE_KI_3            = 6851;
const int FEAT_FREE_KI_4            = 6852;

// Shifter
const int FEAT_PRESTIGE_SHIFTER_NATURALSPELL = 2917;
const int FEAT_PRESTIGE_SHIFTER_EGWSHAPE_1   = 2906;
const int FEAT_PRESTIGE_SHIFTER_GWSHAPE_1    = 2900;
const int SHIFTER_BLACK_LIST                  = 2918;
const int FEAT_SHIFTER_SAVAGERY        = 1822;
const int FEAT_GOREBRUTE_ELITE         = 1810;

//heartwarder
const int FEAT_SANCTIFY_MARTIAL_CLUB        = 3194;
const int FEAT_SANCTIFY_MARTIAL_DAGGER      = 3195;
const int FEAT_SANCTIFY_MARTIAL_MACE        = 3196;
const int FEAT_SANCTIFY_MARTIAL_MORNINGSTAR = 3197;
const int FEAT_SANCTIFY_MARTIAL_QUATERSTAFF = 3198;
const int FEAT_SANCTIFY_MARTIAL_SPEAR       = 3199;
const int FEAT_SANCTIFY_MARTIAL_SHORTSWORD  = 3200;
const int FEAT_SANCTIFY_MARTIAL_RAPIER      = 3201;
const int FEAT_SANCTIFY_MARTIAL_SCIMITAR    = 3202;
const int FEAT_SANCTIFY_MARTIAL_LONGSWORD   = 3203;
const int FEAT_SANCTIFY_MARTIAL_GREATSWORD  = 3204;
const int FEAT_SANCTIFY_MARTIAL_HANDAXE     = 3205;
const int FEAT_SANCTIFY_MARTIAL_BATTLEAXE   = 3206;
const int FEAT_SANCTIFY_MARTIAL_GREATAXE    = 3207;
const int FEAT_SANCTIFY_MARTIAL_HALBERD     = 3208;
const int FEAT_SANCTIFY_MARTIAL_LIGHTHAMMER = 3209;
const int FEAT_SANCTIFY_MARTIAL_LIGHTFLAIL  = 3210;
const int FEAT_SANCTIFY_MARTIAL_WARHAMMER    = 3211;
const int FEAT_SANCTIFY_MARTIAL_HEAVYFLAIL  = 3212;
const int FEAT_SANCTIFY_MARTIAL_SCYTHE      = 3213;
const int FEAT_SANCTIFY_MARTIAL_KATANA      = 3214;
const int FEAT_SANCTIFY_MARTIAL_BASTARDSWORD = 3215;
const int FEAT_SANCTIFY_MARTIAL_DIREMACE    = 3216;
const int FEAT_SANCTIFY_MARTIAL_DOUBLEAXE   = 3217;
const int FEAT_SANCTIFY_MARTIAL_TWOBLADED   = 3218;
const int FEAT_SANCTIFY_MARTIAL_KAMA        = 3219;
const int FEAT_SANCTIFY_MARTIAL_KUKRI       = 3220;
const int FEAT_SANCTIFY_MARTIAL_HEAVYCROSSBOW = 3221;
const int FEAT_SANCTIFY_MARTIAL_LIGHTCROSSBOW = 3222;
const int FEAT_SANCTIFY_MARTIAL_SLING       = 3223;
const int FEAT_SANCTIFY_MARTIAL_LONGBOW     = 3224;
const int FEAT_SANCTIFY_MARTIAL_SHORTBOW    = 3225;
const int FEAT_SANCTIFY_MARTIAL_SHURIKEN    = 3226;
const int FEAT_SANCTIFY_MARTIAL_DART        = 3227;
const int FEAT_SANCTIFY_MARTIAL_DWAXE       = 3170;
const int FEAT_SANCTIFY_MARTIAL_SICKLE      = 3169;
const int FEAT_SANCTIFY_MARTIAL_MINDBLADE   = 3623;

//heartwarder
const int FEAT_CHARISMA_INC1     = 3230;
const int FEAT_CHARISMA_INC2     = 3231;
const int FEAT_CHARISMA_INC3     = 3232;
const int FEAT_CHARISMA_INC4     = 3233;
const int FEAT_CHARISMA_INC5     = 3234;
const int FEAT_HEART_PASSION     = 3235;
const int FEAT_LIPS_RAPTUR       = 3236;
const int FEAT_VOICE_SIREN       = 3237;
const int FEAT_TEARS_EVERGOLD    = 3238;
const int FEAT_FEY_METAMORPH     = 3239;
const int FEAT_ELECTRIC_RES_10   = 3240;
const int FEAT_ELECTRIC_RES_15   = 3241;
const int FEAT_ELECTRIC_RES_20   = 3242;
const int FEAT_ELECTRIC_RES_30   = 3243;
const int FEAT_SHOCK_WEAPON      = 3244;
const int FEAT_THUNDER_WEAPON    = 3245;
const int FEAT_SHOCKING_WEAPON   = 3246;
const int FEAT_ELEMENTAL_CONFLAG = 3247;

// Fist of Raziel
const int FEAT_SMITE_GOOD_ALIGN  = 3248;
const int FEAT_SMITE_CONFIRMING  = 3249;
const int FEAT_SMITE_HOLY        = 3250;
const int FEAT_SMITE_FIEND       = 3251;
const int FEAT_SMITE_CHAIN       = 3252;
const int FEAT_HOLY_MARTIAL_STRIKE = 3228;
const int FEAT_MAGIC_CIRCLE_EVIL = 3229;

const int FEAT_HEALER_10    =   4500;

//Master of Shrouds
const int FEAT_MOS_UNDEAD_1         = 3501;
const int FEAT_MOS_UNDEAD_2         = 3502;
const int FEAT_MOS_UNDEAD_3         = 3503;
const int FEAT_MOS_UNDEAD_4         = 3504;

//Knight of the Chalice
const int DEMONSLAYING_1            = 6854;
const int DEMONSLAYING_2            = 6855;
const int DEMONSLAYING_3            = 6856;
const int DEMONSLAYING_4            = 6857;

//Peerless Archer Feats
const int FEAT_PA_FLETCH_1         = 4284;
const int FEAT_PA_FLETCH_2         = 4285;
const int FEAT_PA_FLETCH_3         = 4286;
const int FEAT_PA_FLETCH_4         = 4287;
const int FEAT_PA_FLETCH_5         = 4288;
const int FEAT_PA_SNEAK_1D6        = 4289;
const int FEAT_PA_SNEAK_2D6        = 4290;
const int FEAT_PA_SNEAK_3D6        = 4291;
const int FEAT_PA_SNEAK_4D6        = 4292;
const int FEAT_PA_POWERSHOT        = 4293;
const int FEAT_PA_IMP_POWERSHOT    = 4294;
const int FEAT_PA_SUP_POWERSHOT    = 4295;
const int FEAT_EXPERT_BOWYER       = 4296;

//Fist of Hextor Feats
const int FEAT_BSTRIKE_A1        = 4246;
const int FEAT_BSTRIKE_A2        = 4247;
const int FEAT_BSTRIKE_A3        = 4248;
const int FEAT_BSTRIKE_A4        = 4249;
const int FEAT_BSTRIKE_A5        = 6783;
const int FEAT_BSTRIKE_A6        = 6784;
const int FEAT_BSTRIKE_A7        = 6785;
const int FEAT_BSTRIKE_A8        = 6786;
const int FEAT_BSTRIKE_A9        = 6787;
const int FEAT_BSTRIKE_A10       = 6788;
const int FEAT_BSTRIKE_A11       = 6789;
const int FEAT_BSTRIKE_A12       = 6790;
const int FEAT_BSTRIKE_D1        = 4242;
const int FEAT_BSTRIKE_D2        = 4243;
const int FEAT_BSTRIKE_D3        = 4244;
const int FEAT_BSTRIKE_D4        = 4245;
const int FEAT_BSTRIKE_D5        = 6769;
const int FEAT_BSTRIKE_D6        = 6770;
const int FEAT_BSTRIKE_D7        = 6771;
const int FEAT_BSTRIKE_D8        = 6772;
const int FEAT_BSTRIKE_D9        = 6773;
const int FEAT_BSTRIKE_D10       = 6774;
const int FEAT_BSTRIKE_D11       = 6775;
const int FEAT_BSTRIKE_D12       = 6776;

//Knight of the Middle Circle
const int FEAT_KOTMC_SL_1        = 6696;
const int FEAT_KOTMC_SL_2        = 6697;
const int FEAT_KOTMC_SL_3        = 6698;

//Thrall of Orcus
const int FEAT_TO_CARRION        = 4404;
const int FEAT_TO_FEAR           = 4405;
const int FEAT_TO_MNR_UNDEAD     = 4409;
const int FEAT_TO_PALLOR         = 4410;
const int FEAT_TO_DEATHTOUCH     = 4411;
const int FEAT_TO_MJR_UNDEAD     = 4412;
const int FEAT_TO_NIGHTWING      = 4413;
const int AOE_MOB_CARRION        = 117;
const int AOE_MOB_PALLOR         = 118;

//True Necromancer
const int AOE_MOB_DES_20       = 111;
const int AOE_MOB_DES_100      = 112;

//Desecrate Effect
const int VFX_TN_DES_20                      = 801;
const int VFX_TN_DES_100                     = 802;

//Black Flame Zealot
const int FEAT_SACRED_FLAME   = 4426;

// Shadowlord
const int SHADOWLORD_BLINDNESS    = 6325;
const int SHADOWLORD_DARKNESS     = 6326;
const int SHADOWLORD_INVISIBILITY = 6327;
const int SHADOWLORD_HASTE        = 6329;
const int SHADOWLORD_IMPROVINVIS  = 6330;
const int SHADOWLORD_VAMPITOUCH   = 6331;
const int SHADOWLORD_CONFUSION    = 6333;
const int SHADOWLORD_INVISPHERE   = 6334;
const int FEAT_SHADOWSPELLLV01    = 3313;
const int FEAT_SHADOWSPELLLV21    = 3317;
const int FEAT_SHADOWSPELLLV31    = 3320;

// Frenzied Berserker Feats
const int FEAT_FRENZY                       = 4300;
const int FEAT_REMOVE_FRENZY                = 4309;
//const int FEAT_GREATER_FRENZY               = 4305;
const int FEAT_INSPIRE_FRENZY               = 4306;
const int FEAT_REMAIN_CONSCIOUS             = 4313;
//const int FEAT_DEATHLESS_FRENZY             = 4314;
const int FEAT_FREBZK_IMPROVED_POWER_ATTACK = 4310;
//const int FEAT_SUPREME_POWER_ATTACK         = 4311;
const int FEAT_INTIMIDATING_RAGE            = 4312;

// Eye of Gruumsh Feats
const int FEAT_COMMAND_THE_HORDE = 4600;
const int FEAT_BLINDING_SPITTLE  = 4601;
const int FEAT_SWING_BLINDLY     = 4602;
const int FEAT_RITUAL_SCARRING   = 4603;
const int FEAT_SIGHT_OF_GRUUMSH  = 4604;
const int FEAT_BLINDSIGHT_5_FT   = 4605;
const int FEAT_BLINDSIGHT_10_FT  = 4606;

// Orc Warlord
const int FEAT_BLOOD_OF_THE_WARLORD = 4608;
const int FEAT_OW_INSPIRE_COURAGE   = 4609;
const int FEAT_FINAL_RAGE           = 4610;
const int FEAT_RELEASE_HORDE        = 4611;
const int FEAT_GATHER_HORDE_I       = 4612;
const int FEAT_GATHER_HORDE_II      = 4613;

// Tempest Feats
//const int FEAT_GREATER_TWO_WEAPON_FIGHTING = 4315;
const int FEAT_SUPREME_TWO_WEAPON_FIGHTING = 4316;
const int FEAT_PERFECT_TWO_WEAPON_FIGHTING = 4320;
//const int FEAT_TWO_WEAPON_DEFENSE  = 4317;
const int FEAT_TWO_WEAPON_DEFENSE2 = 4318;
const int FEAT_TWO_WEAPON_DEFENSE3 = 4319;
const int FEAT_ABSOLUTE_AMBIDEX    = 4321;

// Foe Hunter Feats
const int FEAT_RANCOR = 4322;
const int FEAT_HATED_ENEMY_DR = 4323;
const int FEAT_HATED_ENEMY_SR = 4324;
const int FEAT_FH_DEATH_ATTACK = 4325;

const int FEAT_HATED_ENEMY_DWARF = 4326;
const int FEAT_HATED_ENEMY_ELF = 4327;
const int FEAT_HATED_ENEMY_GNOME = 4328;
const int FEAT_HATED_ENEMY_HALFLING = 4329;
const int FEAT_HATED_ENEMY_HALFELF = 4330;
const int FEAT_HATED_ENEMY_HALFORC = 4331;
const int FEAT_HATED_ENEMY_HUMAN = 4332;
const int FEAT_HATED_ENEMY_ABERRATION = 4333;
const int FEAT_HATED_ENEMY_ANIMAL = 4334;
const int FEAT_HATED_ENEMY_BEAST = 4335;
const int FEAT_HATED_ENEMY_CONSTRUCT = 4336;
const int FEAT_HATED_ENEMY_DRAGON = 4337;
const int FEAT_HATED_ENEMY_GOBLINOID = 4338;
const int FEAT_HATED_ENEMY_MONSTROUS = 4339;
const int FEAT_HATED_ENEMY_ORC = 4340;
const int FEAT_HATED_ENEMY_REPTILIAN = 4341;
const int FEAT_HATED_ENEMY_ELEMENTAL = 4342;
const int FEAT_HATED_ENEMY_FEY = 4343;
const int FEAT_HATED_ENEMY_GIANT = 4344;
const int FEAT_HATED_ENEMY_MAGICAL_BEAST = 4345;
const int FEAT_HATED_ENEMY_OUTSIDER = 4346;
const int FEAT_HATED_ENEMY_SHAPECHANGER = 4347;
const int FEAT_HATED_ENEMY_UNDEAD = 4348;
const int FEAT_HATED_ENEMY_VERMIN = 4349;

// Thrall of Graz'zt
const int FEAT_TOG_SUMMON_DEMON = 2889;

// Shadowlord
const int FEAT_SHADOWBLUR                = 3304;
const int FEAT_SHADOWDISCOPOR            = 3305;
const int FEAT_DEATHATTACK               = 3306;
const int FEAT_SHADOWJUMP                = 3307;
const int FEAT_SHADOWJUMP2               = 3308;
const int FEAT_SHADOWJUMP3               = 3309;
const int FEAT_SHADOWPOUNCE              = 3310;
const int FEAT_SHADOWPOUNCE2             = 3311;
const int FEAT_SHADOWPOUNCE3             = 3312;

// Battleguard Tempus
const int TEMPUS_ENCHANT_WEAPON  = 6320;

// Bonded Summoner
const int FEAT_RESISTANCE_ELE5          = 3322;
const int FEAT_RESISTANCE_ELE10         = 3323;
const int FEAT_RESISTANCE_ELE15         = 3324;
const int FEAT_RESISTANCE_ELE20         = 3325;
const int FEAT_IMMUNITY_SNEAKATK        = 3326;
const int FEAT_IMMUNITY_ELEMENT         = 3327;
const int FEAT_IMMUNITY_CRITIK          = 3328;
const int FEAT_BONDED_AIR               = 3329;
const int FEAT_BONDED_EARTH             = 3330;
const int FEAT_BONDED_FIRE              = 3331;
const int FEAT_BONDED_WATER             = 3332;
const int FEAT_ELE_COMPANION_MED        = 3333;
const int FEAT_ELE_COMPANION_LAR        = 3334;
const int FEAT_ELE_COMPANION_HUG        = 3335;
const int FEAT_ELE_COMPANION_GRE        = 3336;
const int FEAT_ELE_COMPANION_ELD        = 3337;
const int FEAT_TYPE_ELEMENTAL           = 3338;
const int FEAT_SHARE_SPELL              = 3339;

//Sneak Attacks
const int IP_CONST_FEAT_ROGUE_SA_1D6    = 32;
const int IP_CONST_FEAT_ROGUE_SA_2D6    = 33;
const int IP_CONST_FEAT_ROGUE_SA_3D6    = 34;
const int IP_CONST_FEAT_ROGUE_SA_4D6    = 301;
const int IP_CONST_FEAT_ROGUE_SA_5D6    = 39;
const int IP_CONST_FEAT_ROGUE_SA_6D6    = 302;
const int IP_CONST_FEAT_ROGUE_SA_7D6    = 303;
const int IP_CONST_FEAT_ROGUE_SA_8D6    = 304;
const int IP_CONST_FEAT_ROGUE_SA_9D6    = 305;
const int IP_CONST_FEAT_ROGUE_SA_10D6   = 306;
const int IP_CONST_FEAT_ROGUE_SA_11D6   = 307;
const int IP_CONST_FEAT_ROGUE_SA_12D6   = 308;
const int IP_CONST_FEAT_ROGUE_SA_13D6   = 309;
const int IP_CONST_FEAT_ROGUE_SA_14D6   = 310;
const int IP_CONST_FEAT_ROGUE_SA_15D6   = 311;
const int IP_CONST_FEAT_ROGUE_SA_16D6   = 312;
const int IP_CONST_FEAT_ROGUE_SA_17D6   = 313;
const int IP_CONST_FEAT_ROGUE_SA_18D6   = 314;
const int IP_CONST_FEAT_ROGUE_SA_19D6   = 315;
const int IP_CONST_FEAT_ROGUE_SA_20D6   = 316;

const int IP_CONST_FEAT_BG_SA_1D6 = 276;
const int IP_CONST_FEAT_BG_SA_2D6 = 277;
const int IP_CONST_FEAT_BG_SA_3D6 = 278;
const int IP_CONST_FEAT_BG_SA_4D6 = 279;
const int IP_CONST_FEAT_BG_SA_5D6 = 280;
const int IP_CONST_FEAT_BG_SA_6D6 = 281;
const int IP_CONST_FEAT_BG_SA_7D6 = 282;
const int IP_CONST_FEAT_BG_SA_8D6 = 283;
const int IP_CONST_FEAT_BG_SA_9D6 = 284;
const int IP_CONST_FEAT_BG_SA_10D6 = 285;
const int IP_CONST_FEAT_BG_SA_11D6 = 286;
const int IP_CONST_FEAT_BG_SA_12D6 = 287;
const int IP_CONST_FEAT_BG_SA_13D6 = 288;
const int IP_CONST_FEAT_BG_SA_14D6 = 289;
const int IP_CONST_FEAT_BG_SA_15D6 = 290;

const int IP_CONST_FEAT_EPIC_SA_1D6 = 291;
const int IP_CONST_FEAT_EPIC_SA_2D6 = 292;
const int IP_CONST_FEAT_EPIC_SA_3D6 = 293;
const int IP_CONST_FEAT_EPIC_SA_4D6 = 294;
const int IP_CONST_FEAT_EPIC_SA_5D6 = 295;
const int IP_CONST_FEAT_EPIC_SA_6D6 = 296;
const int IP_CONST_FEAT_EPIC_SA_7D6 = 297;
const int IP_CONST_FEAT_EPIC_SA_8D6 = 298;
const int IP_CONST_FEAT_EPIC_SA_9D6 = 299;
const int IP_CONST_FEAT_EPIC_SA_10D6 = 300;

//Iaijutsu Master Feats + Skill

//const int SKILL_IAIJUTSU_FOCUS = 27; //CONSTANT Moved to prc_misc_const
const int FEAT_SKILL_FOCUS_IAI = 6477;
const int FEAT_EPIC_SKILL_FOCUS_IAI = 6478;
const int FEAT_EPIC_IAIJUTSU_FOCUS = 6415; //CONSTANT
const int FEAT_STRIKE_VOID         = 6416; //CONSTANT
const int FEAT_TWO_CUTS            = 6417; //CONSTANT
const int FEAT_ECHOS_EDGE_1        = 6418; //CONSTANT
const int FEAT_ECHOS_EDGE_2        = 6419; //CONSTANT
const int FEAT_ECHOS_EDGE_3        = 6420; //CONSTANT
const int FEAT_ECHOS_EDGE_4        = 6421; //CONSTANT
const int FEAT_ECHOS_EDGE_5        = 6422; //CONSTANT
const int FEAT_ECHOS_EDGE_6        = 6423; //CONSTANT
const int FEAT_SPIRIT_STRIKE_1     = 6424; //CONSTANT
const int FEAT_SPIRIT_STRIKE_2     = 6425; //CONSTANT
const int FEAT_SPIRIT_STRIKE_3     = 6426; //CONSTANT
const int FEAT_SPIRIT_STRIKE_4     = 6427; //CONSTANT
const int FEAT_SPIRIT_STRIKE_5     = 6428; //CONSTANT
const int FEAT_SPIRIT_STRIKE_6     = 6429; //CONSTANT
const int FEAT_KATANA_FINESSE      = 6430; //CONSTANT
const int FEAT_IAIJUTSU_ATTACK     = 6431; //CONSTANT
const int FEAT_EPIC_IAIJUTSU       = 6432;

//Legendary Dread Feats
const int FEAT_UNSTOPPABLE_1         = 6400; //CONSTANT
const int FEAT_UNSTOPPABLE_2         = 6401; //CONSTANT
const int FEAT_UNSTOPPABLE_3         = 6402; //CONSTANT
const int FEAT_UNSTOPPABLE_4         = 6403; //CONSTANT
const int FEAT_UNMOVABLE_1           = 6404; //CONSTANT
const int FEAT_UNMOVABLE_2           = 6405; //CONSTANT
const int FEAT_UNMOVABLE_3           = 6406; //CONSTANT
const int FEAT_UNMOVABLE_4           = 6407; //CONSTANT

//Disciple of Baalzebul Feats
const int FEAT_KING_LIES             = 6408; //CONSTANT
const int FEAT_TONGUE_DEVIL          = 6409; //CONSTANT
const int FEAT_SUGGESTION            = 6410; //CONSTANT
const int FEAT_SUMMON_OSYLUTH        = 6411; //CONSTANT
const int FEAT_INSECT_PLAGUE         = 6412; //CONSTANT
const int FEAT_SUMMON_CORNUGON       = 6413; //CONSTANT
const int FEAT_BEGUILEING_NATURE     = 6414; //CONSTANT

const int FEAT_DEVICE_LORE           = 6433;
const int FEAT_IRON_HEWS             = 6434;
const int FEAT_RUSTING_GRASP         = 6435;
const int FEAT_IRON_POWER_1          = 6436;
const int FEAT_IRON_POWER_2          = 6437;
const int FEAT_SUMMON_ERINYES        = 6438;
const int FEAT_GREATER_IRON_HEWS     = 6439;
const int FEAT_IRON_SKIN             = 6440;
const int FEAT_IRON_BODY             = 6441;

const int FEAT_COFFIN_SANCTUARY      = 6443;
const int FEAT_GASEOUS_FORM          = 6444;

const int FEAT_WEAPON_TEMPUS_CLUB        = 3268;
const int FEAT_WEAPON_TEMPUS_DAGGER      = 3269;
const int FEAT_WEAPON_TEMPUS_MACE        = 3270;
const int FEAT_WEAPON_TEMPUS_MORNINGSTAR = 3271;
const int FEAT_WEAPON_TEMPUS_QUATERSTAFF = 3272;
const int FEAT_WEAPON_TEMPUS_SPEAR       = 3273;
const int FEAT_WEAPON_TEMPUS_SHORTSWORD  = 3274;
const int FEAT_WEAPON_TEMPUS_RAPIER      = 3275;
const int FEAT_WEAPON_TEMPUS_SCIMITAR    = 3276;
const int FEAT_WEAPON_TEMPUS_LONGSWORD   = 3277;
const int FEAT_WEAPON_TEMPUS_GREATSWORD  = 3278;
const int FEAT_WEAPON_TEMPUS_HANDAXE     = 3279;
const int FEAT_WEAPON_TEMPUS_BATTLEAXE   = 3280;
const int FEAT_WEAPON_TEMPUS_GREATAXE    = 3281;
const int FEAT_WEAPON_TEMPUS_HALBERD     = 3282;
const int FEAT_WEAPON_TEMPUS_LIGHTHAMMER = 3283;
const int FEAT_WEAPON_TEMPUS_LIGHTFLAIL  = 3284;
const int FEAT_WEAPON_TEMPUS_WARHAMMER   = 3285;
const int FEAT_WEAPON_TEMPUS_HEAVYFLAIL  = 3286;
const int FEAT_WEAPON_TEMPUS_SCYTHE      = 3287;
const int FEAT_WEAPON_TEMPUS_KATANA      = 3288;
const int FEAT_WEAPON_TEMPUS_BASTARDSWORD= 3289;
const int FEAT_WEAPON_TEMPUS_DIREMACE    = 3290;
const int FEAT_WEAPON_TEMPUS_DOUBLEAXE   = 3291;
const int FEAT_WEAPON_TEMPUS_TWOBLADED   = 3292;
const int FEAT_WEAPON_TEMPUS_KAMA        = 3293;
const int FEAT_WEAPON_TEMPUS_KUKRI       = 3294;
const int FEAT_ARMY_POWER                = 3295;
const int FEAT_BATTLEFORGER              = 3296;
//const int FEAT_DIEHARD                   = 3297;
const int FEAT_ENCHANT_WEAPON1           = 3299;
const int FEAT_ENCHANT_WEAPON2           = 3300;
const int FEAT_ENCHANT_WEAPON3           = 3301;
const int FEAT_WEAPON_TEMPUS_SICKLE      = 3171;
const int FEAT_WEAPON_TEMPUS_DWARVENAXE  = 3172;
const int FEAT_WEAPON_TEMPUS_MINDBLADE   = 3625;


// Initiate of Draconic
const int FEAT_CLAWDRAGON               = 3341;
const int FEAT_INCREASE_DAMAGE1         = 3342;
const int FEAT_INCREASE_DAMAGE2         = 3343;
const int FEAT_INIDR_SPELLRESISTANCE    = 3345;
const int FEAT_INIDR_STUNSTRIKE         = 3346;
const int FEAT_INIDR_SHAPEDRAGON        = 3347;
const int FEAT_CLAWENH2                 = 3348;
const int FEAT_CLAWENH3                 = 3349;
const int FEAT_EPIC_INCREASE_DAMAGE1    = 3186;
const int FEAT_EPIC_INCREASE_DAMAGE2    = 3187;
const int FEAT_EPIC_INCREASE_DAMAGE3    = 3188;
const int FEAT_EPIC_INCREASE_DAMAGE4    = 3189;
const int FEAT_EPIC_INCREASE_DAMAGE5    = 3177;

// BladeSinger

const int FEAT_BLADESONG_STYLE          = 3190;
const int FEAT_LESSER_SPELLSONG         = 3191;
const int FEAT_GREATER_SPELLSONG        = 3192;
const int FEAT_SONG_OF_FURY             = 3193;

// Archer

const int FEAT_EXTRASHOT                = 3180;
const int FEAT_BOWSPEC2                 = 3181;
const int FEAT_BOWSPEC3                 = 3182;
const int FEAT_BOWSPEC4                 = 3183;
const int FEAT_BOWSPEC5                 = 3184;
const int FEAT_BOWSPEC6                 = 3185;
const int FEAT_BOWSPEC7                 = 3107;
const int FEAT_BOWSPEC8                 = 3108;
const int FEAT_BOWSPEC9                 = 3109;

const int FEAT_KILLINGSHOT              = 3352;
const int FEAT_PERFECTSHOT              = 3353;
const int FEAT_PERFECTSHOT2             = 3354;

const int FEAT_BOWMASTERY               = 3174;
const int FEAT_XBOWMASTERY              = 3175;
const int FEAT_SHURIKENMASTERY          = 3176;

// Man At Arm

const int FEAT_GENERAL_SPECIALIZATION   = 3100;
const int FEAT_MASTER_CRITICAL          = 3101;
const int FEAT_FOCUSED_STRIKE           = 3102;
const int FEAT_STRIKE_AT_CORE           = 3103;
const int FEAT_FURIOUS_ASSAULT          = 3104;
const int FEAT_LEGENDARY_PROWESS        = 3105;


//Soldier of Light
const int FEAT_SOL_DIVINE_GRACE                  = 3140;
const int FEAT_SMITE_UNDEAD                      = 3139;
const int FEAT_POSITIVE_FORTITUDE                = 3140;
const int FEAT_ENERGON_COMPANION                 = 3141;
const int FEAT_POSITIVE_ENERGY_BURST             = 3146;
const int FEAT_SOL_FAST_HEALING_1                = 3137;
const int FEAT_SOL_FAST_HEALING_2                = 3138;
const int FEAT_SOL_FAST_HEALING_3                = 3314;
const int FEAT_MAXIMIZE_TURNING                  = 3315;
const int FEAT_SUP_POSITIVE_ENERGY_BURST         = 3316;



// Blood Archer

const int FEAT_BLARCH_POISON_BLOOD      = 4200;

// Henshin Mystic                                  feat.2da  spell.2da
const int FEAT_PRESTIGE_RIDDLE_OF_AWARENESS        = 4020;   // 2260
const int FEAT_PRESTIGE_HAPPO_ZANSHIN              = 4021;   // 2261
const int FEAT_PRESTIGE_RIDDLE_OF_INTERACTION      = 4022;   // 2262
const int FEAT_PRESTIGE_BLINDSIGHT                 = 4023;   // 2263
const int FEAT_PRESTIGE_HITSU_DO                   = 4024;   // 2264
const int FEAT_PRESTIGE_WALK_THROUGH_THE_MOUNTAINS = 4025;   // 2265
const int FEAT_PRESTIGE_RIDDLE_OF_INVULNERABILITY  = 4026;   // 2266

// Drunken Master
const int FEAT_PRESTIGE_DRINK_LIKE_A_DEMON         = 4027;   // 2267
const int FEAT_PRESTIGE_BOTTLE_PROFICIENCY         = 4028;   // 2268
const int FEAT_PRESTIGE_STAGGER                    = 4029;   // 2269
const int FEAT_PRESTIGE_SWAYING_WAIST              = 4030;   // 2270
const int FEAT_PRESTIGE_DRUNKEN_RAGE               = 4031;   // 2271
const int FEAT_PRESTIGE_LURCH                      = 4032;   // 2272
const int FEAT_PRESTIGE_DRUNKEN_EMBRACE            = 4033;   // 2273
const int FEAT_PRESTIGE_FOR_MEDICINAL_PURPOSES     = 4034;   // 2274
const int FEAT_PRESTIGE_BREATH_OF_FLAME            = 4035;   // 2275

//Hathran class feats
const int FEAT_HATH_COHORT          = 6671; //CONSTANT
const int FEAT_HATH_COMMAND         = 6672; //CONSTANT
const int FEAT_HATH_FEAR1           = 6675; //CONSTANT
const int FEAT_HATH_FEAR2           = 6676; //CONSTANT
const int FEAT_HATH_FEAR3           = 6677; //CONSTANT

//Vigilant class feats
const int FEAT_VIGIL_ARMOR          = 6670; //CONSTANT
const int FEAT_SPRINT               = 6673; //CONSTANT
const int FEAT_VIGIL_HEAL           = 6674; //CONSTANT

//Prerequisitie feats (Hathran and Vigilant)
const int FEAT_ETHRAN               = 6667; //CONSTANT
const int FEAT_ENDURANCE            = 6668; //CONSTANT
//const int FEAT_TRACK                = 6669; //CONSTANT

// Sacred Fist
const int FEAT_SF_AC1               = 2933;
const int FEAT_SF_AC2               = 2934;
const int FEAT_SF_AC3               = 2935;
const int FEAT_SF_AC4               = 2936;
const int FEAT_SF_AC5               = 2937;
const int FEAT_SF_AC6               = 2938;
const int FEAT_SF_AC7               = 2939;
const int FEAT_SF_UNARMEDDMG        = 2932;
const int FEAT_SF_INNERARMOR        = 2940;
const int FEAT_SF_SACREDFLAME1      = 2941;
const int FEAT_SF_SACREDFLAME2      = 2942;
const int FEAT_SF_SACREDFLAME3      = 2943;
const int FEAT_SF_SACREDFLAME4      = 2944;
const int FEAT_SF_SACREDFLAME5      = 2945;
const int FEAT_SF_SACREDFLAME6      = 2946;
const int FEAT_SF_SACREDFLAME7      = 2947;
const int FEAT_SF_SPEED1            = 2948;
const int FEAT_SF_SPEED2            = 2949;
const int FEAT_SF_SPEED3            = 2950;
const int FEAT_SF_CODE              = 2951;

// Shadow Adept

const int FEAT_SA_SHADOWDEF1        = 2952;
const int FEAT_SA_SHADOWDEF2        = 2953;
const int FEAT_SA_SHADOWDEF3        = 2954;
const int FEAT_SA_SHADOWDEPIC       = 2955;
const int FEAT_SA_SHIELDSHADOW      = 2956;
const int FEAT_SA_GREATSHIELDSHADOW = 2957;
const int FEAT_SA_SHADOWWALK        = 2958;
const int FEAT_SA_SHADOWDOUBLE      = 2959;

// Brawler
const int FEAT_BRAWLER_FISTS                     = 4428;
const int FEAT_EPIC_BRAWLER                      = 4437;
const int FEAT_BRAWLER_BLOCK_1                   = 4438;
const int FEAT_BRAWLER_BLOCK_2                   = 4439;
const int FEAT_BRAWLER_BLOCK_3                   = 4440;
const int FEAT_BRAWLER_BLOCK_4                   = 4441;
const int FEAT_BRAWLER_BLOCK_5                   = 4442;
const int FEAT_BRAWLER_EXTRAATT_1                = 4429;
const int FEAT_BRAWLER_EXTRAATT_2                = 4430;
const int FEAT_BRAWLER_EXTRAATT_3                = 4431;
const int FEAT_BRAWLER_DAMAGE_REDUCTION_3        = 4432;
const int FEAT_BRAWLER_DAMAGE_REDUCTION_6        = 4433;
const int FEAT_BRAWLER_DAMAGE_REDUCTION_9        = 4434;

// Minstrel of the Edge
const int FEAT_MINSTREL_LIGHT_ARMOR_CASTING      = 4435;
const int FEAT_MINSTREL_SONG_SLEEP               = 4443;
const int FEAT_MINSTREL_SONG_SILENCE             = 4444;
const int FEAT_MINSTREL_SONG_HASTE               = 4445;
const int FEAT_MINSTREL_SONG_SLOW                = 4446;
const int FEAT_MINSTREL_SONG_CHARM               = 4447;
const int FEAT_MINSTREL_SONG_IMM_FEAR            = 4449;
const int FEAT_MINSTREL_SONG_SHIELD_AC           = 4450;
const int FEAT_MINSTREL_SONG_SONIC_WEAP          = 4451;
const int FEAT_MINSTREL_SONG_STRENGTH            = 4452;
const int FEAT_MINSTREL_SONG_DEXTERITY           = 4453;
const int FEAT_MINSTREL_SONG_CONSTITUTION        = 4454;
const int FEAT_MINSTREL_SONG_INTELLIGENCE        = 4455;
const int FEAT_MINSTREL_SONG_WISDOM              = 4456;
const int FEAT_MINSTREL_SONG_CHARISMA            = 4457;
const int FEAT_MINSTREL_SONG_WOUND_WHISP         = 4458;
const int FEAT_MINSTREL_GREATER_MINSTREL_SONG    = 4448;

// Nightshade
const int FEAT_NS_LIGHT_ADAPTION    = 2964;
const int FEAT_NS_WEBWALKER         = 2965;
const int FEAT_NS_SNEAKATK_1D6      = 2966;
const int FEAT_NS_SNEAKATK_2D6      = 2967;
const int FEAT_NS_SNEAKATK_3D6      = 2968;
const int FEAT_NS_INVISIBILITY      = 2969;
const int FEAT_NS_POISON_IMMUNE     = 2970;
const int FEAT_NS_POISON_SPITTLE    = 2971;
const int FEAT_NS_WEB               = 2972;
const int FEAT_NS_SHADOWWALK        = 2973;

// Runescarred Berserker

const int FEAT_RIT_SCAR             = 6469;
const int FEAT_SPAWNFROST           = 6471;
const int FEAT_RIT_DR               = 6470;
const int FEAT_RIT_SCAR_2           = 6475;
const int FEAT_RIT_SCAR_3           = 6476;

// Ultimate Ranger

const int FEAT_UR_FE_DWARF          = 2974;
const int FEAT_UR_FE_ELF            = 2975;
const int FEAT_UR_FE_GNOME          = 2976;
const int FEAT_UR_FE_HALFING        = 2977;
const int FEAT_UR_FE_HALFELF        = 2978;
const int FEAT_UR_FE_HALFORC        = 2979;
const int FEAT_UR_FE_HUMAN          = 2980;
const int FEAT_UR_FE_ABERRATION     = 2981;
const int FEAT_UR_FE_ANIMAL         = 2982;
const int FEAT_UR_FE_BEAST          = 2983;
const int FEAT_UR_FE_CONSTRUCT      = 2984;
const int FEAT_UR_FE_DRAGON         = 2985;
const int FEAT_UR_FE_GOBLINOID      = 2986;
const int FEAT_UR_FE_MONSTROUS      = 2987;
const int FEAT_UR_FE_ORC            = 2988;
const int FEAT_UR_FE_REPTILIAN      = 2989;
const int FEAT_UR_FE_ELEMENTAL      = 2990;
const int FEAT_UR_FE_FEY            = 2991;
const int FEAT_UR_FE_GIANT          = 2992;
const int FEAT_UR_FE_MAGICAL_BEAST  = 2993;
const int FEAT_UR_FE_OUTSIDER       = 2994;
const int FEAT_UR_FE_SHAPECHANGER   = 2995;
const int FEAT_UR_FE_UNDEAD         = 2996;
const int FEAT_UR_FE_VERMIN         = 2997;
const int FEAT_UR_SNAREMASTERY      = 2998;
const int FEAT_UR_SNEAKATK_3D6      = 2999;
const int FEAT_UR_ARMOREDGRACE      = 3430;
const int FEAT_UR_DODGE_FE          = 3431;
const int FEAT_UR_RESIST_FE         = 3432;
const int FEAT_UR_HAWK_TOTEM        = 3433;
const int FEAT_UR_OWL_TOTEM         = 3434;
const int FEAT_UR_VIPER_TOTEM       = 3435;
const int FEAT_UR_GRACE1            = 3436;
const int FEAT_UR_GRACE2            = 3437;
const int FEAT_UR_GRACE3            = 3438;
const int FEAT_UR_GRACE4            = 3439;
const int FEAT_UR_FAST_MOVEMENT     = 3097;
const int FEAT_UNCANNYX_DODGE_1     = 3098;
const int FEAT_LINGERING_DAMAGE     = 3099;
const int FEAT_UR_HIPS              = 3457;

// Dragonsong Lyrith
const int FEAT_DRAGONSONG_STRENGTH      = 3441;
const int FEAT_DRAGONSONG_COMPULSION    = 3442;
const int FEAT_DRAGONSONG_SPEED         = 3443;
const int FEAT_DRAGONSONG_FEAR          = 3444;
const int FEAT_DRAGONSONG_HEALING       = 3445;
const int FEAT_EPIC_DRAGONSONG_STRENGTH      = 3496;
const int FEAT_EPIC_DRAGONSONG_COMPULSION    = 3497;
const int FEAT_EPIC_DRAGONSONG_SPEED         = 3498;
const int FEAT_EPIC_DRAGONSONG_FEAR          = 3499;
const int FEAT_EPIC_DRAGONSONG_HEALING       = 3500;
const int FEAT_FOCUS_DRAGONSONG              = 3318;
const int FEAT_GREATER_FOCUS_DRAGONSONG      = 3319;
const int FEAT_EPIC_FOCUS_DRAGONSONG         = 3321;

// Favored of Milil
const int FEAT_FOM_DIVINE_SONG_BLESS               = 4459;
const int FEAT_FOM_DIVINE_SONG_CONVICTION          = 4460;
const int FEAT_FOM_DIVINE_SONG_CURELIGHT           = 4461;
const int FEAT_FOM_DIVINE_SONG_REMOVEFEAR          = 4462;
const int FEAT_FOM_DIVINE_SONG_SANCTUARY           = 4463;
const int FEAT_FOM_DIVINE_SONG_SHIELDFAITH         = 4464;
const int FEAT_FOM_DIVINE_SONG_AID                 = 4465;
const int FEAT_FOM_DIVINE_SONG_BULLSTRENGTH        = 4466;
const int FEAT_FOM_DIVINE_SONG_CUREMODERATE        = 4467;
const int FEAT_FOM_DIVINE_SONG_EAGLESPLENDOR       = 4468;
const int FEAT_FOM_DIVINE_SONG_ENDURANCE           = 4469;
const int FEAT_FOM_DIVINE_SONG_FOXCUNNING          = 4470;
const int FEAT_FOM_DIVINE_SONG_LESSRESTORE         = 4471;
const int FEAT_FOM_DIVINE_SONG_OWLWISDOM           = 4472;
const int FEAT_FOM_DIVINE_SONG_CLAIRVOYANCE        = 4473;
const int FEAT_FOM_DIVINE_SONG_CLARITY             = 4474;
const int FEAT_FOM_DIVINE_SONG_CURESERIOUS         = 4475;
const int FEAT_FOM_DIVINE_SONG_NEGATIVEPROT        = 4476;
const int FEAT_FOM_DIVINE_SONG_PRAYER              = 4477;
const int FEAT_FOM_DIVINE_SONG_PROTELEMENTS        = 4478;
const int FEAT_FOM_DIVINE_SONG_REMOVECURSE         = 4479;
const int FEAT_FOM_DIVINE_SONG_CURECRITICAL        = 4480;
const int FEAT_FOM_DIVINE_SONG_DEATHWARD           = 4481;
const int FEAT_FOM_DIVINE_SONG_FREEDOMMOVEMENT     = 4482;
const int FEAT_FOM_DIVINE_SONG_PANACEA             = 4483;
const int FEAT_FOM_DIVINE_SONG_RESTORATION         = 4484;
const int FEAT_FOM_DIVINE_SONG_STONESKIN           = 4485;
const int FEAT_FOM_DIVINE_SONG_TRUESEEING          = 4486;
const int FEAT_FOM_DIVINE_SONG_MONSTREGEN          = 4487;
const int FEAT_FOM_DIVINE_SONG_RAISEDEAD           = 4488;
const int FEAT_FOM_DIVINE_SONG_SPELLRESISTANCE     = 4489;
const int FEAT_FOM_ENCORE_PERFORMANCE         = 4436;

// Evil-Paladin
const int FEAT_HIDDENFAITH                       = 3484;
const int FEAT_AP_TURN_OUTSIDER                  = 3486;

// Outlaw Crimson Road
const int FEAT_FUGITIVE_LUCK1                    = 6898;
const int FEAT_FUGITIVE_LUCK2                    = 6899;
const int FEAT_FUGITIVE_LUCK3                    = 2877;
const int FEAT_FUGITIVE_LUCKEPIC                 = 2879;
const int FEAT_OUT_LEADERSHIP                    = 2880;
const int FEAT_OUT_LEGENDS                       = 2881;

//  Alaghar
const int FEAT_CLANGEDDINS_STRIKE                = 3991;
const int FEAT_CLANGEDDINS_MIGHT                 = 3992;
const int FEAT_ALAG_SILVERBEARD                  = 3993;
const int FEAT_ALAG_ROCKBURST                    = 3994;

// Combat Medic
const int FEAT_HEALING_KICKER_1                  = 3540;
const int FEAT_HEALING_KICKER_2                  = 3541;
const int FEAT_HEALING_KICKER_3                  = 3542;

// Crafting
const int FEAT_CRAFT_WONDROUS            = 2925;
const int FEAT_CRAFT_ARMS_ARMOR          = 2926;
const int FEAT_CRAFT_ROD                 = 2927;
const int FEAT_CRAFT_STAFF               = 2928;
const int FEAT_FORGE_RING                = 2929;
const int FEAT_CRAFT_CONSTRUCT           = 2920;
const int FEAT_CRAFT_ITEM                = 2919;//combined with read recepie, was 2899
const int FEAT_CRAFT_EPIC_WONDROUS_ITEM  = 3488;
const int FEAT_CRAFT_EPIC_MAGIC_ARMS_ARMOR = 3489;
const int FEAT_CRAFT_EPIC_ROD            = 3490;
const int FEAT_CRAFT_EPIC_STAFF          = 3491;
const int FEAT_FORGE_EPIC_RING           = 3528;

// Exalted Companion
const int FEAT_EXALTED_COMPANION         = 4199;

// Dragon Disciple
const int FEAT_RED_DRAGON                        = 4100;
const int FEAT_SILVER_DRAGON                     = 4101;
const int FEAT_BLACK_DRAGON                      = 4102;
const int FEAT_BLUE_DRAGON                       = 4103;
const int FEAT_GREEN_DRAGON                      = 4104;
const int FEAT_WHITE_DRAGON                      = 4105;
const int FEAT_BRASS_DRAGON                      = 4106;
const int FEAT_BRONZE_DRAGON                     = 4107;
const int FEAT_COPPER_DRAGON                     = 4108;
const int FEAT_GOLD_DRAGON                       = 4109;
const int FEAT_AMETHYST_DRAGON                   = 4110;
const int FEAT_CRYSTAL_DRAGON                    = 4111;
const int FEAT_EMERALD_DRAGON                    = 4112;
const int FEAT_SAPPHIRE_DRAGON                   = 4113;
const int FEAT_TOPAZ_DRAGON                      = 4114;
const int FEAT_BATTLE_DRAGON                     = 4115;
const int FEAT_BROWN_DRAGON                      = 4116;
const int FEAT_CHAOS_DRAGON                      = 4117;
const int FEAT_DEEP_DRAGON                       = 4118;
const int FEAT_ETHEREAL_DRAGON                   = 4119;
const int FEAT_FANG_DRAGON                       = 4120;
const int FEAT_HOWLING_DRAGON                    = 4121;
const int FEAT_OCEANUS_DRAGON                    = 4122;
const int FEAT_PYROCLASTIC_DRAGON                = 4123;
const int FEAT_RADIANT_DRAGON                    = 4124;
const int FEAT_RUST_DRAGON                       = 4125;
const int FEAT_SHADOW_DRAGON                     = 4126;
const int FEAT_SONG_DRAGON                       = 4127;
const int FEAT_STYX_DRAGON                       = 4128;
const int FEAT_TARTIAN_DRAGON                    = 4129;
const int FEAT_DRACONIC_IMMUNITY                 = 4130;
const int FEAT_CHIANG_LUNG_DRAGON                = 4131;
const int FEAT_LI_LUNG_DRAGON                    = 4132;
const int FEAT_LUNG_WANG_DRAGON                  = 4133;
const int FEAT_PAN_LUNG_DRAGON                   = 4134;
const int FEAT_SHEN_LUNG_DRAGON                  = 4135;
const int FEAT_TIEN_LUNG_DRAGON                  = 4136;
const int FEAT_TUN_MI_LUNG_DRAGON                = 4137;
const int FEAT_YU_LUNG_DRAGON                    = 4138;
const int FEAT_DRAGON_DIS_BREATH_2               = 4139;
const int FEAT_DRAGON_DIS_BREATH_3               = 4140;
const int FEAT_DRAGON_DIS_BREATH_4               = 4141;
const int FEAT_DRAGON_DIS_BREATH_5               = 4142;
const int FEAT_DRAGON_DIS_BREATH_6               = 4143;
const int FEAT_DRAGON_DIS_BREATH_7               = 4144;
const int DRACONIC_ARMOR_AUG_1                   = 4148;
const int DRACONIC_SPELLRESIST                   = 4149;
const int DRACONIC_ARMOR_AUG_2                   = 4150;
const int DRAGON_BLOODED                         = 4151;
const int FEAT_DRACONIC_SIZE_INCREASE_1          = 4152;
const int FEAT_DRACONIC_SIZE_INCREASE_2          = 4153;
const int DRACONIC_CLAWS                         = 4162;
const int DRACONIC_BITE                          = 4163;
const int DRACONIC_WINGSLAMS                     = 4164;
const int DRACONIC_TAILSLAP                      = 4165;

// Complete Adv Ninja
const int FEAT_EPIC_ACROBATICS_8    = 6584;
const int FEAT_EPIC_ACROBATICS_10   = 6585;
const int FEAT_EPIC_ACROBATICS_12   = 6586;
const int FEAT_EPIC_NINJA_CA        = 6587;
const int FEAT_KI_POWER         = 6588;
const int FEAT_ACROBATICS_2         = 6589;
const int FEAT_ACROBATICS_4         = 6590;
const int FEAT_ACROBATICS_6     = 6591;
const int FEAT_GHOST_SIGHT      = 6592;
const int FEAT_GHOST_STEP       = 6593;
const int FEAT_GHOST_STRIKE     = 6594;
const int FEAT_GHOST_WALK       = 6595;
const int FEAT_GREAT_LEAP       = 6596;
const int FEAT_GREATER_KI_DODGE     = 6597;
const int FEAT_KI_DODGE         = 6598;
const int FEAT_GHOST_STEP_2         = 6599;

//Alienist
const int FEAT_SUMMON_ALIEN                      = 1572;
const int FEAT_ALIEN_BLESSING                    = 1573;
const int FEAT_MAD_CERTAINTY                     = 1574;
const int FEAT_PSEUDONATURAL_FAMILIAR            = 1575;
const int FEAT_EXTRA_SUMMONING                   = 1576;
const int FEAT_INSANE_CERTAINTY                  = 1577;
const int FEAT_TRANSCENDENCE                     = 1578;

// Fast Healing
const int FAST_HEALING_1                         = 4145;
const int FAST_HEALING_2                         = 4146;
const int FAST_HEALING_3                         = 4147;

// General Feats
const int FEAT_STORMMAGIC            = 4182;
const int FEAT_MAGICAL_APTITUDE          = 4416;

// Size changes
const int FEAT_SIZE_DECREASE_1          = 6387;
const int FEAT_SIZE_DECREASE_2          = 6388;
const int FEAT_SIZE_DECREASE_3          = 6389;
const int FEAT_SIZE_DECREASE_4          = 6390;
const int FEAT_SIZE_DECREASE_5          = 6391;
const int FEAT_SIZE_DECREASE_6          = 6392;
const int FEAT_SIZE_INCREASE_1          = 6393;
const int FEAT_SIZE_INCREASE_2          = 6394;
const int FEAT_SIZE_INCREASE_3          = 6395;
const int FEAT_SIZE_INCREASE_4          = 6396;
const int FEAT_SIZE_INCREASE_5          = 6397;
const int FEAT_SIZE_INCREASE_6          = 6398;



/*//////////////////////////////////////////////////
////////////////CODI STUFF//////////////////////////
//////////////////////////////////////////////////*/

//Ninja Spy
const int SPELLABILITY_NS_MEDIUM                 = 1528;
const int SPELLABILITY_NS_SMALL                  = 1529;
const int SPELLABILITY_NS_DWARF                  = 1530;
const int SPELLABILITY_NS_ELF                    = 1531;
const int SPELLABILITY_NS_HALF_ELF               = 1532;
const int SPELLABILITY_NS_HALF_ORC               = 1533;
const int SPELLABILITY_NS_HUMAN                  = 1534;
const int SPELLABILITY_NS_GNOME                  = 1535;
const int SPELLABILITY_NS_HALFLING               = 1536;
const int SPELLABILITY_NS_OFF                    = 1537;

const int FEAT_EPIC_NINJA                        = 3426;
const int FEAT_1000FACES_MEDIUM                  = 3400;
const int FEAT_1000FACES_SMALL                   = 3401;
const int FEAT_1000FACES_OFF                     = 3402;

//Mystic Theurge
const int FEAT_EPIC_THEURGE                      = 3427;

//War Priest
const int SPELLABILITY_WP_RALLY                  = 1549;
const int SPELLABILITY_WP_INFLAME                = 1550;
const int SPELLABILITY_WP_IMPLACABLE_FOE         = 1551;

const int FEAT_EPIC_WARPRIEST                    = 3428;
const int FEAT_RALLY                             = 3418;
const int FEAT_INFLAME                           = 3419;
const int FEAT_IMPLACABLE_FOE                    = 3420;
const int FEAT_HEALING_CIRCLE                    = 3421;
const int FEAT_FEAR_AURA                         = 3422;
const int FEAT_MASS_HASTE                        = 3423;
const int FEAT_MASS_HEAL                         = 3424;

//Ocular Adept
const int SPELLABILITY_OA_CHPERRAY               = 1538;
const int SPELLABILITY_OA_SLEEPRAY               = 1539;
const int SPELLABILITY_OA_INFRAY                 = 1540;
const int SPELLABILITY_OA_SLOWRAY                = 1541;
const int SPELLABILITY_OA_FEARRAY                = 1542;
const int SPELLABILITY_OA_CHMONRAY               = 1543;
const int SPELLABILITY_OA_TELERAY                = 1544;
const int SPELLABILITY_OA_PETRAY                 = 1545;
const int SPELLABILITY_OA_DISRAY                 = 1546;
const int SPELLABILITY_OA_DEATHRAY               = 1547;

const int FEAT_CHPERRAY                          = 3403;
const int FEAT_SLEEPRAY                          = 3404;
const int FEAT_INFRAY                            = 3405;
const int FEAT_SLOWRAY                           = 3406;
const int FEAT_FEARRAY                           = 3407;
const int FEAT_CHMONRAY                          = 3408;
const int FEAT_TELERAY                           = 3409;
const int FEAT_PETRAY                            = 3410;
const int FEAT_DISRAY                            = 3411;
const int FEAT_DEATHRAY                          = 3412;

//Samurai
const int SPELLABILITY_SM_ANCESTDAISHO           = 1548;

const int FEAT_EPIC_SAMURAI                      = 3416;
const int FEAT_ANCESTRAL_DAISHO                  = 3417;
const int FEAT_EPIC_ANCESTRAL_DAISHO_1           = 6050;
const int FEAT_EPIC_ANCESTRAL_DAISHO_2           = 6051;
const int FEAT_EPIC_ANCESTRAL_DAISHO_3           = 6052;
const int FEAT_EPIC_ANCESTRAL_DAISHO_4           = 6053;
const int FEAT_EPIC_ANCESTRAL_DAISHO_5           = 6054;
const int FEAT_EPIC_ANCESTRAL_DAISHO_6           = 6055;
const int FEAT_EPIC_ANCESTRAL_DAISHO_7           = 6056;
const int FEAT_EPIC_ANCESTRAL_DAISHO_8           = 6057;
const int FEAT_EPIC_ANCESTRAL_DAISHO_9           = 6058;
const int FEAT_EPIC_ANCESTRAL_DAISHO_10          = 6059;

//Battlerager
const int FEAT_BATTLE_RAGE1                      = 3413;
const int FEAT_BATTLE_RAGE2                      = 3414;
const int FEAT_BATTLE_RAGE3                      = 3415;
const int FEAT_BATTLE_RAGE4                      = 3505;
const int FEAT_BATTLE_RAGE5                      = 3506;
const int FEAT_BATTLE_RAGE6                      = 3507;
const int FEAT_BATTLE_RAGE7                      = 3508;
const int FEAT_BATTLE_RAGE8                      = 3509;
const int FEAT_BATTLE_RAGE9                      = 3510;
const int FEAT_BATTLE_RAGE10                     = 3511;
const int FEAT_FEROCIOUS_PROW                    = 3512;
const int FEAT_PRC_EPIC_MIGHT_RAGE               = 3516;

/*//////////////////////////////////////////////////////
//////////////////////END CODI//////////////////////////
//////////////////////////////////////////////////////*/


/*//////////////////////////////////////////////////
//////////////// PSIONICS //////////////////////////
//////////////////////////////////////////////////*/

//Psion
const int FEAT_PSION_DIS_EGOIST                     = 3554;
const int FEAT_PSION_DIS_KINETICIST                 = 3555;
const int FEAT_PSION_DIS_NOMAD                      = 3556;
const int FEAT_PSION_DIS_SEER                       = 3557;
const int FEAT_PSION_DIS_SHAPER                     = 3558;
const int FEAT_PSION_DIS_TELEPATH                   = 3559;

//Wilder
const int FEAT_WILDER_SURGING_EUPHORIA              = 3568;
const int FEAT_WILDER_PSYCHIC_ENERVATION            = 3569;
const int FEAT_WILDER_VOLATILE_MIND                 = 3570;
const int FEAT_WILDER_ELUDE_TOUCH                   = 3567;
const int FEAT_WILDER_WILD_SURGE_1_5                = 3560;
const int FEAT_WILDER_WILD_SURGE_6_10               = 3561;
const int FEAT_WILDER_WILD_SURGE_11                 = 3562;

// Soulknife
const int FEAT_MINDBLADE                            = 3600;
const int FEAT_MANIFEST_MINDBLADE                   = 3601;
const int FEAT_WEAPON_FOCUS_MINDBLADE               = 3602;
const int FEAT_GREATER_WEAPON_FOCUS_MINDBLADE       = 3603;
const int FEAT_THROW_MINDBLADE                      = 3604;
const int FEAT_PSYCHIC_STRIKE                       = 3605;
const int FEAT_FREE_DRAW                            = 3606;
const int FEAT_SHAPE_MINDBLADE                      = 3607;
const int FEAT_MINDBLADE_ENHANCEMENT                = 3608;
const int FEAT_BLADEWIND                            = 3609;
const int FEAT_KNIFE_TO_THE_SOUL                    = 3610;
const int FEAT_KNIFE_TO_THE_SOUL_RADIAL1            = 3611;
const int FEAT_KNIFE_TO_THE_SOUL_RADIAL2            = 3612;
const int FEAT_EPIC_SOULKNIFE                       = 3613;
const int FEAT_IMPROVED_CRITICAL_MINDBLADE          = 3614;
const int FEAT_OVERWHELMING_CRITICAL_MINDBLADE      = 3615;
const int FEAT_DEVASTATING_CRITICAL_MINDBLADE       = 3616;
const int FEAT_WEAPON_SPECIALIZATION_MINDBLADE      = 3617;
const int FEAT_EPIC_WEAPON_FOCUS_MINDBLADE          = 3618;
const int FEAT_EPIC_WEAPON_SPECIALIZATION_MINDBLADE = 3619;
const int FEAT_MULTIPLE_THROW                       = 3620;
const int FEAT_CHANGE_HANDEDNESS                    = 3621;
const int FEAT_WEAPON_OF_CHOICE_MINDBLADE           = 3622;

//Psionic Feats
const int FEAT_MENTAL_RESISTANCE                    = 4812;
const int FEAT_HOSTILE_MIND                         = 4813;
const int FEAT_FORCE_OF_WILL                        = 4814;
const int FEAT_CLOSED_MIND                          = 4815;
const int FEAT_RECKLESS_OFFENSE                     = 4816;
const int FEAT_CLOAK_DANCE                          = 4817;
const int FEAT_PSIONIC_FOCUS                        = 4818;
const int FEAT_PSIONIC_HOLE                         = 4811;
const int FEAT_COMBAT_MANIFESTATION                 = 4810;
const int FEAT_MENTAL_LEAP                          = 4809;
const int FEAT_NARROW_MIND                          = 4808;
const int FEAT_POWER_PENETRATION                    = 4807;
const int FEAT_GREATER_POWER_PENETRATION            = 4806;
const int FEAT_POWER_SPECIALIZATION                 = 4805;
const int FEAT_GREATER_POWER_SPECIALIZATION         = 4804;
const int FEAT_PSIONIC_DODGE                        = 4803;
const int FEAT_PSIONIC_ENDOWMENT                    = 4802;
const int FEAT_GREATER_PSIONIC_ENDOWMENT            = 4801;
const int FEAT_PSIONIC_FIST                         = 4800;
const int FEAT_GREATER_PSIONIC_FIST                 = 4821;
const int FEAT_PSIONIC_WEAPON                       = 4822;
const int FEAT_GREATER_PSIONIC_WEAPON               = 4823;
const int FEAT_PSIONIC_SHOT                         = 4824;
const int FEAT_GREATER_PSIONIC_SHOT                 = 4825;
const int FEAT_OVERCHANNEL                          = 4826;
const int FEAT_PSIONIC_MEDITATION                   = 4827;
const int FEAT_RAPID_METABOLISM                     = 4828;
const int FEAT_TALENTED                             = 4829;
const int FEAT_UNAVOIDABLE_STRIKE                   = 4830;
const int FEAT_WILD_TALENT                          = 4831;
const int FEAT_WOUNDING_ATTACK                      = 4832;
const int FEAT_BOOST_CONSTRUCT                      = 4833;
const int FEAT_SPEED_OF_THOUGHT                     = 4834;
const int FEAT_PSIONIC_TALENT_1                     = 4835;
const int FEAT_PSIONIC_TALENT_2                     = 4836;
const int FEAT_PSIONIC_TALENT_3                     = 4837;
const int FEAT_PSIONIC_TALENT_4                     = 4838;
const int FEAT_PSIONIC_TALENT_5                     = 4839;
const int FEAT_PSIONIC_TALENT_6                     = 4840;
const int FEAT_PSIONIC_TALENT_7                     = 4841;
const int FEAT_PSIONIC_TALENT_8                     = 4842;
const int FEAT_PSIONIC_TALENT_9                     = 4843;
const int FEAT_PSIONIC_TALENT_10                    = 4844;
const int FEAT_METAMORPHIC_TRANSFER_1               = 4845;
const int FEAT_METAMORPHIC_TRANSFER_2               = 4846;
const int FEAT_METAMORPHIC_TRANSFER_3               = 4847;
const int FEAT_METAMORPHIC_TRANSFER_4               = 4848;
const int FEAT_METAMORPHIC_TRANSFER_5               = 4849;
const int FEAT_METAMORPHIC_TRANSFER_6               = 4850;
const int FEAT_METAMORPHIC_TRANSFER_7               = 4851;
const int FEAT_DEEP_IMPACT                          = 4852;
const int FEAT_FELL_SHOT                            = 4853;
const int FEAT_EXPANDED_KNOWLEDGE_1                 = 4867;
const int FEAT_EXPANDED_KNOWLEDGE_2                 = 4868;
const int FEAT_EXPANDED_KNOWLEDGE_3                 = 4869;
const int FEAT_EXPANDED_KNOWLEDGE_4                 = 4870;
const int FEAT_EXPANDED_KNOWLEDGE_5                 = 4871;
const int FEAT_EXPANDED_KNOWLEDGE_6                 = 4872;
const int FEAT_EXPANDED_KNOWLEDGE_7                 = 4873;
const int FEAT_EXPANDED_KNOWLEDGE_8                 = 4874;
const int FEAT_EXPANDED_KNOWLEDGE_9                 = 4875;
const int FEAT_EXPANDED_KNOWLEDGE_10                = 4876;
const int FEAT_INVEST_ARMOUR                        = 3643;

// Epic psionic feats
const int FEAT_EPIC_PSIONIC_FOCUS_1                 = 4857;
const int FEAT_EPIC_PSIONIC_FOCUS_2                 = 4858;
const int FEAT_EPIC_PSIONIC_FOCUS_3                 = 4859;
const int FEAT_EPIC_PSIONIC_FOCUS_4                 = 4860;
const int FEAT_EPIC_PSIONIC_FOCUS_5                 = 4861;
const int FEAT_EPIC_PSIONIC_FOCUS_6                 = 4862;
const int FEAT_EPIC_PSIONIC_FOCUS_7                 = 4863;
const int FEAT_EPIC_PSIONIC_FOCUS_8                 = 4864;
const int FEAT_EPIC_PSIONIC_FOCUS_9                 = 4865;
const int FEAT_EPIC_PSIONIC_FOCUS_10                = 4866;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_1            = 4877;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_2            = 4878;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_3            = 4879;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_4            = 4880;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_5            = 4881;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_6            = 4882;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_7            = 4883;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_8            = 4884;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_9            = 4885;
const int FEAT_EPIC_EXPANDED_KNOWLEDGE_10           = 4886;
const int FEAT_IMPROVED_METAPSIONICS_1              = 4887;
const int FEAT_IMPROVED_METAPSIONICS_2              = 4888;
const int FEAT_IMPROVED_METAPSIONICS_3              = 4889;
const int FEAT_IMPROVED_METAPSIONICS_4              = 4890;
const int FEAT_IMPROVED_METAPSIONICS_5              = 4891;
const int FEAT_IMPROVED_METAPSIONICS_6              = 4892;
const int FEAT_IMPROVED_METAPSIONICS_7              = 4893;
const int FEAT_IMPROVED_METAPSIONICS_8              = 4894;
const int FEAT_IMPROVED_METAPSIONICS_9              = 4895;
const int FEAT_IMPROVED_METAPSIONICS_10             = 4896;
const int FEAT_IMPROVED_MANIFESTATION_1             = 4897;
const int FEAT_IMPROVED_MANIFESTATION_2             = 4898;
const int FEAT_IMPROVED_MANIFESTATION_3             = 4899;
const int FEAT_IMPROVED_MANIFESTATION_4             = 4900;
const int FEAT_IMPROVED_MANIFESTATION_5             = 4901;
const int FEAT_IMPROVED_MANIFESTATION_6             = 4902;
const int FEAT_IMPROVED_MANIFESTATION_7             = 4903;
const int FEAT_IMPROVED_MANIFESTATION_8             = 4904;
const int FEAT_IMPROVED_MANIFESTATION_9             = 4905;
const int FEAT_IMPROVED_MANIFESTATION_10            = 4906;
const int FEAT_POWER_KNOWLEDGE_PSION_1              = 4907;
const int FEAT_POWER_KNOWLEDGE_PSION_2              = 4908;
const int FEAT_POWER_KNOWLEDGE_PSION_3              = 4909;
const int FEAT_POWER_KNOWLEDGE_PSION_4              = 4910;
const int FEAT_POWER_KNOWLEDGE_PSION_5              = 4911;
const int FEAT_POWER_KNOWLEDGE_PSION_6              = 4912;
const int FEAT_POWER_KNOWLEDGE_PSION_7              = 4913;
const int FEAT_POWER_KNOWLEDGE_PSION_8              = 4914;
const int FEAT_POWER_KNOWLEDGE_PSION_9              = 4915;
const int FEAT_POWER_KNOWLEDGE_PSION_10             = 4916;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_1             = 4917;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_2             = 4918;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_3             = 4919;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_4             = 4920;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_5             = 4921;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_6             = 4922;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_7             = 4923;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_8             = 4924;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_9             = 4925;
const int FEAT_POWER_KNOWLEDGE_PSYWAR_10            = 4926;
const int FEAT_POWER_KNOWLEDGE_WILDER_1             = 4927;
const int FEAT_POWER_KNOWLEDGE_WILDER_2             = 4928;
const int FEAT_POWER_KNOWLEDGE_WILDER_3             = 4929;
const int FEAT_POWER_KNOWLEDGE_WILDER_4             = 4930;
const int FEAT_POWER_KNOWLEDGE_WILDER_5             = 4931;
const int FEAT_POWER_KNOWLEDGE_WILDER_6             = 4932;
const int FEAT_POWER_KNOWLEDGE_WILDER_7             = 4933;
const int FEAT_POWER_KNOWLEDGE_WILDER_8             = 4934;
const int FEAT_POWER_KNOWLEDGE_WILDER_9             = 4935;
const int FEAT_POWER_KNOWLEDGE_WILDER_10            = 4936;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_1     = 4945;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_2     = 4946;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_3     = 4947;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_4     = 4948;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_5     = 4949;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_6     = 4950;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_7     = 4951;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_8     = 4952;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_9     = 4953;
const int FEAT_POWER_KNOWLEDGE_FIST_OF_ZUOKEN_10    = 4954;
const int FEAT_POWER_KNOWLEDGE_WARMIND_1            = 4955;
const int FEAT_POWER_KNOWLEDGE_WARMIND_2            = 4956;
const int FEAT_POWER_KNOWLEDGE_WARMIND_3            = 4957;
const int FEAT_POWER_KNOWLEDGE_WARMIND_4            = 4958;
const int FEAT_POWER_KNOWLEDGE_WARMIND_5            = 4959;
const int FEAT_POWER_KNOWLEDGE_WARMIND_6            = 4960;
const int FEAT_POWER_KNOWLEDGE_WARMIND_7            = 4961;
const int FEAT_POWER_KNOWLEDGE_WARMIND_8            = 4962;
const int FEAT_POWER_KNOWLEDGE_WARMIND_9            = 4963;
const int FEAT_POWER_KNOWLEDGE_WARMIND_10           = 4964;

// Metapsionic feats
const int FEAT_CHAIN_POWER                          = 4937;
const int FEAT_EMPOWER_POWER                        = 4938;
const int FEAT_EXTEND_POWER                         = 4939;
const int FEAT_MAXIMIZE_POWER                       = 4940;
const int FEAT_SPLIT_PSIONIC_RAY                    = 4941;
const int FEAT_TWIN_POWER                           = 4942;
const int FEAT_WIDEN_POWER                          = 4943;
const int FEAT_QUICKEN_POWER                        = 4944;

// Sanctified Mind
const int FEAT_SANCMIND_PARTITION_MIND              = -1;

/*//////////////////////////////////////////////////
//////////////// END PSIONICS //////////////////////
//////////////////////////////////////////////////*/

// Swashbuckler
const int FEAT_SWASH_GRACE1                         = 6000;
const int FEAT_SWASH_GRACE2                         = 6001;
const int FEAT_SWASH_GRACE3                         = 6002;
const int FEAT_SWASH_GRACE4                         = 6003;
const int FEAT_SWASH_GRACE5                         = 6004;
const int INSIGHTFUL_STRIKE                         = 6005;
const int SWASH_DODGE_1                             = 6006;
const int SWASH_DODGE_2                             = 6007;
const int SWASH_DODGE_3                             = 6008;
const int SWASH_DODGE_4                             = 6009;
const int SWASH_DODGE_5                             = 6010;
const int SWASH_DODGE_6                             = 6011;
const int SWASH_DODGE_7                             = 6012;
const int SWASH_DODGE_8                             = 6013;
const int SWASH_LUCKY                               = 6014;
const int WEAKENING_CRITICAL                        = 6015;
const int WOUNDING_CRITICAL                         = 6016;

//Marshal
const int MIN_AUR_FORT                         = 6019;
const int MIN_AUR_WILL                         = 6020;
const int MIN_AUR_REF                          = 6021;
const int MIN_AUR_CHA                          = 6022;
const int MIN_AUR_CON                          = 6023;
const int MIN_AUR_DEX                          = 6024;
const int MIN_AUR_INT                          = 6025;
const int MIN_AUR_STR                          = 6026;
const int MIN_AUR_WIS                          = 6027;
const int MIN_AUR_CAST                         = 6028;
const int MIN_AUR_AOW                          = 6029;
const int MAJ_AUR_MOT_ARDOR                    = 6030;
const int MAJ_AUR_MOT_CARE                     = 6031;
const int MAJ_AUR_RES_TROOPS                   = 6032;
const int MAJ_AUR_MOT_URGE                     = 6033;
const int MAJ_AUR_HARD_SOLDIER                 = 6034;
const int MAJ_AUR_MOT_ATTACK                   = 6035;
const int MAJ_AUR_STEAD_HAND                   = 6036;
const int GRANT_MOVE_ACTION                    = 6037;
const int MINOR_AURA                           = 6038;
const int MAJOR_AURA                           = 6039;


//ACP feat
const int FEAT_ACP_FEAT                       = 2892;

// Epic Spellcasting Rest feat
const int FEAT_EPIC_SPELLCASTING_REST         = 4399;

//Baelnorn
const int FEAT_END_PROJECTION                 = 3575;
const int FEAT_BAELN_PROP                     = 3576;
const int FEAT_BAELN_TOUCH                    = 3577;
const int FEAT_BAELN_ABIL                     = 3578;
const int FEAT_PROJECTION                     = 3579;
const int FEAT_BAELN_DEF                      = 3580;
//const int FEAT_UNDEAD_HD                      = 3581;
//const int FEAT_TURN_RESISTANCE                = 3582;
const int FEAT_IMPROVED_TURN_RESISTANCE       = 3583;
const int FEAT_IMMUNITY_ABILITY_DECREASE      = 3584;
const int FEAT_IMMUNITY_CRITICAL              = 3585;
const int FEAT_IMMUNITY_DEATH                 = 3586;
const int FEAT_IMMUNITY_DISEASE               = 3587;
const int FEAT_IMMUNITY_MIND_SPELLS           = 3588;
const int FEAT_IMMUNITY_PARALYSIS             = 3589;
const int FEAT_IMMUNITY_POISON                = 3590;
const int FEAT_IMMUNITY_SNEAKATTACK           = 3591;
const int FEAT_POSITIVE_ENERGY_RESISTANCE     = 3592;
const int FEAT_TURNING_IMMUNITY               = 3593;

//Mother Cyst
const int FEAT_MOTHER_CYST                    = 3594;

//Tenjac's spell related
const int FEAT_DETECT_GOOD_AT_WILL            = 3595;
const int FEAT_RAY_CHARM_PERSON               = 6328;
const int FEAT_RAY_CHARM_MONSTER              = 6329;
const int FEAT_RAY_SLEEP                      = 6330;
const int FEAT_RAY_FLESH_TO_STONE             = 6331;
const int FEAT_RAY_DISINTEGRATE               = 6332;
const int FEAT_RAY_FEAR                       = 6333;
const int FEAT_RAY_SLOW                       = 6334;
const int FEAT_RAY_INFLICT_MODERATE_WOUNDS    = 6335;
const int FEAT_RAY_FINGER_OF_DEATH            = 6336;

//Lasher
const int FEAT_LASHER_SNEAK1D6                = 4075;
const int FEAT_LASHER_SNEAK2D6                = 4076;
const int FEAT_LASHER_SNEAK3D6                = 4077;
const int FEAT_LASHER_IMPROVED_KNOCKDOWN_WHIP = 4078;
const int FEAT_LASHER_THIRD_HAND              = 4079;
const int FEAT_LASHER_CRACK_FATE              = 4080;
const int FEAT_LASHER_LASHING_WHIP            = 4081;
const int FEAT_LASHER_IMPROVED_DISARM_WHIP    = 4082;
const int FEAT_LASHER_STUNNING_SNAP           = 4083;
const int FEAT_LASHER_CRACK_DOOM              = 4084;
const int FEAT_LASHER_DEATH_SPIRAL            = 4085;

// PnP Spell Schools
const int FEAT_PNP_SPELL_SCHOOL_GENERAL       = 6373;
const int FEAT_PNP_SPELL_SCHOOL_ABJURATION    = 6374;
const int FEAT_PNP_SPELL_SCHOOL_CONJURATION   = 6375;
const int FEAT_PNP_SPELL_SCHOOL_DIVINATION    = 6376;
const int FEAT_PNP_SPELL_SCHOOL_ENCHANTMENT   = 6377;
const int FEAT_PNP_SPELL_SCHOOL_EVOCATION     = 6378;
const int FEAT_PNP_SPELL_SCHOOL_ILLUSION      = 6379;
const int FEAT_PNP_SPELL_SCHOOL_NECROMANCY    = 6380;
const int FEAT_PNP_SPELL_SCHOOL_TRANSMUTATION = 6381;

//Spellfire
const int FEAT_SPELLFIRE_WIELDER              = 4368;
const int FEAT_SPELLFIRE_INCREASE             = 4369;
const int FEAT_SPELLFIRE_DECREASE             = 4370;
const int FEAT_SPELLFIRE_QUICKSELECT          = 4371;
const int FEAT_WEAPON_FOCUS_SPELLFIRE         = 4372;
const int FEAT_EPIC_WEAPON_FOCUS_SPELLFIRE    = 4373;
const int FEAT_SPELLFIRE_DRAIN_CHARGED        = 4374;
const int FEAT_SPELLFIRE_INCREASED_STORAGE    = 4375;
const int FEAT_SPELLFIRE_IMPROVED_HEALING     = 4376;
const int FEAT_SPELLFIRE_RAPID_BLAST          = 4377;
const int FEAT_SPELLFIRE_CHARGE_ITEM          = 4378;
const int FEAT_SPELLFIRE_CROWN                = 4379;
const int FEAT_SPELLFIRE_MAELSTROM            = 4380;

// Favoured Soul
const int FEAT_FAVOURED_SOUL_ACID             = 6337;
const int FEAT_FAVOURED_SOUL_COLD             = 6338;
const int FEAT_FAVOURED_SOUL_ELEC             = 6339;
const int FEAT_FAVOURED_SOUL_FIRE             = 6340;
const int FEAT_FAVOURED_SOUL_SONIC            = 6341;
const int FEAT_FAVOURED_SOUL_WINGS            = 6342;
const int FEAT_FAVOURED_SOUL_DAMRED           = 6343;

//Shadowblade
const int FEAT_UNSEEN_WEAPON_UNERRING_STRIKE  = 3650;
const int FEAT_SHADOW_AND_STEALTH             = 3651;
const int FEAT_SUDDEN_STRIKE                  = 3652;
const int FEAT_UNSEEN_WEAPON_UNEXPECTED_STRIKE= 3653;
const int FEAT_UNSEEN_WEAPON_EPHEMERAL_WEAPON = 3654;
const int FEAT_UNSEEN_WEAPON_SHADOWY_STRIKE   = 3655;
const int FEAT_UNSEEN_WEAPON_FAR_SHADOW       = 3656;
const int FEAT_UNSEEN_WEAPON_FREE_ACTION      = 3657;
const int FEAT_ULTRAVISION                    = 3658;

// War Wizard of Cormyr
const int FEAT_WWOC_WIDEN_SPELL               = 6573;
const int FEAT_WWOC_ENLARGE_SPELL_AREA        = 6574;

// Complete Warrior Samurai
const int FEAT_CWSM_STAREDOWN                 = 6456;
const int FEAT_CWSM_MASS_STAREDOWN            = 6457;
const int FEAT_CWSM_IMPROVED_STAREDOWN        = 6458;
const int FEAT_CWSM_FRIGHTFUL_PRESENCE        = 6459;

 // Virtuoso Feats
 const int FEAT_VIRTUOSO_SUSTAINING_SONG       = 4168;
 const int FEAT_VIRTUOSO_CALUMNY               = 4169;
 const int FEAT_VIRTUOSO_JARRING_SONG          = 4170;
 const int FEAT_VIRTUOSO_SHARP_NOTE            = 4171;
 const int FEAT_VIRTUOSO_MINDBENDING_MELODY    = 4172;
 const int FEAT_VIRTUOSO_GREATER_CALUMNY       = 4173;
 const int FEAT_VIRTUOSO_MAGICAL_MELODY        = 4174;
 const int FEAT_VIRTUOSO_SONG_OF_FURY          = 4175;
 const int FEAT_VIRTUOSO_REVEALING_MELODY      = 4176;
 const int FEAT_VIRTUOSO_PERFORMANCE           = 4177;

// Status markers
const int FEAT_INCORPOREAL                    = 4166;
const int FEAT_ETHEREAL                       = 4167;


// Template Feats
const int FEAT_TEMPLATE_CELESTIAL_SMITE_EVIL  = 22601;
const int FEAT_TEMPLATE_CELESTIAL_MARKER      = 22602;
const int FEAT_TEMPLATE_FIENDISH_SMITE_GOOD         = 22603;
 const int FEAT_TEMPLATE_FIENDISH_MARKER             = 22604;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_SMITE_EVIL   = 22605;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_PROTECTION   = 22606;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_BLESS        = 22607;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_AID          = 22608;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_DETECT       = 22609;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_CURE_SERIOUS = 22610;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_NEUTRALIZE_POISON = 22611;
 //const int FEAT_TEMPLATE_FIENDISH_MARKER             = 22612;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_REMOVE_DISEASE= 22613;
 //const int FEAT_TEMPLATE_FIENDISH_MARKER             = 22614;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_HOLY_WORD    = 22615;
 //const int FEAT_TEMPLATE_FIENDISH_MARKER             = 22616;
 //const int FEAT_TEMPLATE_FIENDISH_MARKER             = 22617;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_MASS_CHARM   = 22618;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_SUMMON_IX    = 22619;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_RESURRECTION = 22620;
 //const int FEAT_TEMPLATE_HALF_CELESTIAL_DAYLIGHT     = 22621;
 const int FEAT_TEMPLATE_HALF_CELESTIAL_MARKER       = 22622;

 // PRC Extra Stunning Feat
 const int FEAT_PRC_EXTRA_STUNNING             = 4387;

 // Enlightened Fist Feats
 const int FEAT_EF_FIST_OF_ENERGY              = 4388;
 const int FEAT_EF_SPELL_SELECT                = 4389;
 const int FEAT_EF_ARCANE_FIST                 = 4390;
 const int FEAT_EF_ARCANE_REJUVENATION         = 4391;
 const int FEAT_EF_HOLD_RAY                    = 4392;
 const int FEAT_EF_DIAMOND_SOUL                = 4393;
 const int FEAT_EF_UNARMEDDMG                  = 4394;
 const int FEAT_EF_SPEED                       = 4395;
 const int FEAT_EF_EXTRA_STUNNING              = 4396;
 const int FEAT_EF_FIST_OF_ENERGY_BURST        = 4397;

 //BONUS SPELL FEATS

const int FEAT_AOTS_SPELLCST_WIZ               = 7000;
const int FEAT_AOTS_SPELLCST_SORC              = 7001;
const int FEAT_AOTS_SPELLCST_BARD              = 7002;
const int FEAT_AOTS_SPELLCST_ASSN              = 7003;
const int FEAT_AOTS_SPELLCST_SUEL              = 7004;
const int FEAT_AOTS_SPELLCST_SHDL              = 7005;
const int FEAT_AOTS_SPELLCST_HEXBLD            = 7006;
const int FEAT_AOTS_SPELLCST_DSKBLD            = 7007;
const int FEAT_MHARP_SPELLCST_WIZ              = 7008;
const int FEAT_MHARP_SPELLCST_SORC             = 7009;
const int FEAT_MHARP_SPELLCST_BARD             = 7010;
const int FEAT_MHARP_SPELLCST_ASSN             = 7011;
const int FEAT_MHARP_SPELLCST_SUEL             = 7012;
const int FEAT_MHARP_SPELLCST_SHDL             = 7013;
const int FEAT_MHARP_SPELLCST_HEXBLD           = 7014;
const int FEAT_MHARP_SPELLCST_DSKBLD           = 7015;
const int FEAT_MHARP_SPELLCST_CLER             = 7016;
const int FEAT_MHARP_SPELLCST_DRUID            = 7017;
const int FEAT_MHARP_SPELLCST_PAL              = 7018;
const int FEAT_MHARP_SPELLCST_RNG              = 7019;
const int FEAT_MHARP_SPELLCST_BLKG             = 7020;
const int FEAT_MHARP_SPELLCST_SOL              = 7021;
const int FEAT_MHARP_SPELLCST_VASSAL           = 7022;
const int FEAT_MHARP_SPELLCST_KMC              = 7023;
const int FEAT_MHARP_SPELLCST_KCH              = 7024;
const int FEAT_MHARP_SPELLCST_APAL             = 7025;
const int FEAT_MHARP_SPELLCST_VGL              = 7026;
const int FEAT_MHARP_SPELLCST_FVS              = 7027;
const int FEAT_MHARP_SPELLCST_SOHEI            = 7028;
const int FEAT_MHARP_SPELLCST_HLR              = 7029;
const int FEAT_MHARP_SPELLCST_SOD              = 7030;
const int FEAT_MHARP_SPELLCST_OCULAR           = 7031;
const int FEAT_ARCTRK_SPELLCST_WIZ             = 7032;
const int FEAT_ARCTRK_SPELLCST_SORC            = 7033;
const int FEAT_ARCTRK_SPELLCST_BARD            = 7034;
const int FEAT_ARCTRK_SPELLCST_ASSN            = 7035;
const int FEAT_ARCTRK_SPELLCST_SUEL            = 7036;
const int FEAT_ARCTRK_SPELLCST_SHDL            = 7037;
const int FEAT_ARCTRK_SPELLCST_HEXBLD          = 7038;
const int FEAT_ARCTRK_SPELLCST_DSKBLD          = 7039;
const int FEAT_ARCH_SPELLCST_WIZ               = 7040;
const int FEAT_ARCH_SPELLCST_SORC              = 7041;
const int FEAT_ARCH_SPELLCST_BARD              = 7042;
const int FEAT_ARCH_SPELLCST_ASSN              = 7043;
const int FEAT_ARCH_SPELLCST_SUEL              = 7044;
const int FEAT_ARCH_SPELLCST_SHDL              = 7045;
const int FEAT_ARCH_SPELLCST_HEXBLD            = 7046;
const int FEAT_ARCH_SPELLCST_DSKBLD            = 7047;
const int FEAT_TEMPUS_SPELLCST_CLER            = 7048;
const int FEAT_TEMPUS_SPELLCST_DRUID           = 7049;
const int FEAT_TEMPUS_SPELLCST_PAL             = 7050;
const int FEAT_TEMPUS_SPELLCST_RNG             = 7051;
const int FEAT_TEMPUS_SPELLCST_BLKG            = 7052;
const int FEAT_TEMPUS_SPELLCST_SOL             = 7053;
const int FEAT_TEMPUS_SPELLCST_VASSAL          = 7054;
const int FEAT_TEMPUS_SPELLCST_KMC             = 7055;
const int FEAT_TEMPUS_SPELLCST_KCH             = 7056;
const int FEAT_TEMPUS_SPELLCST_APAL            = 7057;
const int FEAT_TEMPUS_SPELLCST_VGL             = 7058;
const int FEAT_TEMPUS_SPELLCST_FVS             = 7059;
const int FEAT_TEMPUS_SPELLCST_SOHEI           = 7060;
const int FEAT_TEMPUS_SPELLCST_HLR             = 7061;
const int FEAT_TEMPUS_SPELLCST_SOD             = 7062;
const int FEAT_TEMPUS_SPELLCST_OCULAR          = 7063;
const int FEAT_BFZ_SPELLCST_CLER               = 7064;
const int FEAT_BFZ_SPELLCST_DRUID              = 7065;
const int FEAT_BFZ_SPELLCST_PAL                = 7066;
const int FEAT_BFZ_SPELLCST_RNG                = 7067;
const int FEAT_BFZ_SPELLCST_BLKG               = 7068;
const int FEAT_BFZ_SPELLCST_SOL                = 7069;
const int FEAT_BFZ_SPELLCST_VASSAL             = 7070;
const int FEAT_BFZ_SPELLCST_KMC                = 7071;
const int FEAT_BFZ_SPELLCST_KCH                = 7072;
const int FEAT_BFZ_SPELLCST_APAL               = 7073;
const int FEAT_BFZ_SPELLCST_VGL                = 7074;
const int FEAT_BFZ_SPELLCST_FVS                = 7075;
const int FEAT_BFZ_SPELLCST_SOHEI              = 7076;
const int FEAT_BFZ_SPELLCST_HLR                = 7077;
const int FEAT_BFZ_SPELLCST_SOD                = 7078;
const int FEAT_BFZ_SPELLCST_OCULAR             = 7079;
const int FEAT_BLADES_SPELLCST_WIZ             = 7080;
const int FEAT_BLADES_SPELLCST_SORC            = 7081;
const int FEAT_BLADES_SPELLCST_BARD            = 7082;
const int FEAT_BLADES_SPELLCST_ASSN            = 7083;
const int FEAT_BLADES_SPELLCST_SUEL            = 7084;
const int FEAT_BLADES_SPELLCST_SHDL            = 7085;
const int FEAT_BLADES_SPELLCST_HEXBLD          = 7086;
const int FEAT_BLADES_SPELLCST_DSKBLD          = 7087;
const int FEAT_BLMAGUS_SPELLCST_WIZ            = 7088;
const int FEAT_BLMAGUS_SPELLCST_SORC           = 7089;
const int FEAT_BLMAGUS_SPELLCST_BARD           = 7090;
const int FEAT_BLMAGUS_SPELLCST_ASSN           = 7091;
const int FEAT_BLMAGUS_SPELLCST_SUEL           = 7092;
const int FEAT_BLMAGUS_SPELLCST_SHDL           = 7093;
const int FEAT_BLMAGUS_SPELLCST_HEXBLD         = 7094;
const int FEAT_BLMAGUS_SPELLCST_DSKBLD         = 7095;
const int FEAT_BONDED_SPELLCST_WIZ             = 7096;
const int FEAT_BONDED_SPELLCST_SORC            = 7097;
const int FEAT_BONDED_SPELLCST_BARD            = 7098;
const int FEAT_BONDED_SPELLCST_ASSN            = 7099;
const int FEAT_BONDED_SPELLCST_SUEL            = 7100;
const int FEAT_BONDED_SPELLCST_SHDL            = 7101;
const int FEAT_BONDED_SPELLCST_HEXBLD          = 7102;
const int FEAT_BONDED_SPELLCST_DSKBLD          = 7103;
const int FEAT_BONDED_SPELLCST_CLER            = 7104;
const int FEAT_BONDED_SPELLCST_DRUID           = 7105;
const int FEAT_BONDED_SPELLCST_PAL             = 7106;
const int FEAT_BONDED_SPELLCST_RNG             = 7107;
const int FEAT_BONDED_SPELLCST_BLKG            = 7108;
const int FEAT_BONDED_SPELLCST_SOL             = 7109;
const int FEAT_BONDED_SPELLCST_VASSAL          = 7110;
const int FEAT_BONDED_SPELLCST_KMC             = 7111;
const int FEAT_BONDED_SPELLCST_KCH             = 7112;
const int FEAT_BONDED_SPELLCST_APAL            = 7113;
const int FEAT_BONDED_SPELLCST_VGL             = 7114;
const int FEAT_BONDED_SPELLCST_FVS             = 7115;
const int FEAT_BONDED_SPELLCST_SOHEI           = 7116;
const int FEAT_BONDED_SPELLCST_HLR             = 7117;
const int FEAT_BONDED_SPELLCST_SOD             = 7118;
const int FEAT_BONDED_SPELLCST_OCULAR          = 7119;
const int FEAT_CEREB_SPELLCST_WIZ              = 7120;
const int FEAT_CEREB_SPELLCST_SORC             = 7121;
const int FEAT_CEREB_SPELLCST_BARD             = 7122;
const int FEAT_CEREB_SPELLCST_ASSN             = 7123;
const int FEAT_CEREB_SPELLCST_SUEL             = 7124;
const int FEAT_CEREB_SPELLCST_SHDL             = 7125;
const int FEAT_CEREB_SPELLCST_HEXBLD           = 7126;
const int FEAT_CEREB_SPELLCST_DSKBLD           = 7127;
const int FEAT_CEREB_SPELLCST_PSION            = 7128;
const int FEAT_CEREB_SPELLCST_PSYCH            = 7129;
const int FEAT_CEREB_SPELLCST_WILDER           = 7130;
const int FEAT_CEREB_SPELLCST_WARMIND          = 7131;
const int FEAT_CEREB_SPELLCST_FISTZ            = 7132;
const int FEAT_CBTMED_SPELLCST_BARD            = 7133;
const int FEAT_CBTMED_SPELLCST_CLER            = 7134;
const int FEAT_CBTMED_SPELLCST_DRUID           = 7135;
const int FEAT_CBTMED_SPELLCST_PAL             = 7136;
const int FEAT_CBTMED_SPELLCST_RNG             = 7137;
const int FEAT_CBTMED_SPELLCST_BLKG            = 7138;
const int FEAT_CBTMED_SPELLCST_SOL             = 7139;
const int FEAT_CBTMED_SPELLCST_KMC             = 7140;
const int FEAT_CBTMED_SPELLCST_FVS             = 7141;
const int FEAT_CBTMED_SPELLCST_HLR             = 7142;
const int FEAT_CBTMED_SPELLCST_OCULAR          = 7143;
const int FEAT_BRIMST_SPELLCST_CLER            = 7144;
const int FEAT_BRIMST_SPELLCST_DRUID           = 7145;
const int FEAT_BRIMST_SPELLCST_PAL             = 7146;
const int FEAT_BRIMST_SPELLCST_RNG             = 7147;
const int FEAT_BRIMST_SPELLCST_BLKG            = 7148;
const int FEAT_BRIMST_SPELLCST_SOL             = 7149;
const int FEAT_BRIMST_SPELLCST_VASSAL          = 7150;
const int FEAT_BRIMST_SPELLCST_KMC             = 7151;
const int FEAT_BRIMST_SPELLCST_KCH             = 7152;
const int FEAT_BRIMST_SPELLCST_APAL            = 7153;
const int FEAT_BRIMST_SPELLCST_VGL             = 7154;
const int FEAT_BRIMST_SPELLCST_FVS             = 7155;
const int FEAT_BRIMST_SPELLCST_SOHEI           = 7156;
const int FEAT_BRIMST_SPELLCST_HLR             = 7157;
const int FEAT_BRIMST_SPELLCST_SOD             = 7158;
const int FEAT_BRIMST_SPELLCST_OCULAR          = 7159;
const int FEAT_CNTMP_SPELLCST_CLER             = 7160;
const int FEAT_CNTMP_SPELLCST_DRUID            = 7161;
const int FEAT_CNTMP_SPELLCST_PAL              = 7162;
const int FEAT_CNTMP_SPELLCST_RNG              = 7163;
const int FEAT_CNTMP_SPELLCST_BLKG             = 7164;
const int FEAT_CNTMP_SPELLCST_SOL              = 7165;
const int FEAT_CNTMP_SPELLCST_VASSAL           = 7166;
const int FEAT_CNTMP_SPELLCST_KMC              = 7167;
const int FEAT_CNTMP_SPELLCST_KCH              = 7168;
const int FEAT_CNTMP_SPELLCST_APAL             = 7169;
const int FEAT_CNTMP_SPELLCST_VGL              = 7170;
const int FEAT_CNTMP_SPELLCST_FVS              = 7171;
const int FEAT_CNTMP_SPELLCST_SOHEI            = 7172;
const int FEAT_CNTMP_SPELLCST_HLR              = 7173;
const int FEAT_CNTMP_SPELLCST_SOD              = 7174;
const int FEAT_CNTMP_SPELLCST_OCULAR           = 7175;
const int FEAT_DIABOL_SPELLCST_WIZ             = 7176;
const int FEAT_DIABOL_SPELLCST_SORC            = 7177;
const int FEAT_DIABOL_SPELLCST_BARD            = 7178;
const int FEAT_DIABOL_SPELLCST_ASSN            = 7179;
const int FEAT_DIABOL_SPELLCST_SUEL            = 7180;
const int FEAT_DIABOL_SPELLCST_SHDL            = 7181;
const int FEAT_DIABOL_SPELLCST_HEXBLD          = 7182;
const int FEAT_DIABOL_SPELLCST_DSKBLD          = 7183;
const int FEAT_DOA_SPELLCST_WIZ                = 7184;
const int FEAT_DOA_SPELLCST_SORC               = 7185;
const int FEAT_DOA_SPELLCST_BARD               = 7186;
const int FEAT_DOA_SPELLCST_ASSN               = 7187;
const int FEAT_DOA_SPELLCST_SUEL               = 7188;
const int FEAT_DOA_SPELLCST_SHDL               = 7189;
const int FEAT_DOA_SPELLCST_HEXBLD             = 7190;
const int FEAT_DOA_SPELLCST_DSKBLD             = 7191;
const int FEAT_SAVANT_SPELLCST_WIZ             = 7192;
const int FEAT_SAVANT_SPELLCST_SORC            = 7193;
const int FEAT_SAVANT_SPELLCST_BARD            = 7194;
const int FEAT_SAVANT_SPELLCST_ASSN            = 7195;
const int FEAT_SAVANT_SPELLCST_SUEL            = 7196;
const int FEAT_SAVANT_SPELLCST_SHDL            = 7197;
const int FEAT_SAVANT_SPELLCST_HEXBLD          = 7198;
const int FEAT_SAVANT_SPELLCST_DSKBLD          = 7199;
const int FEAT_SAVANT_SPELLCST_CLER            = 7200;
const int FEAT_SAVANT_SPELLCST_DRUID           = 7201;
const int FEAT_SAVANT_SPELLCST_PAL             = 7202;
const int FEAT_SAVANT_SPELLCST_RNG             = 7203;
const int FEAT_SAVANT_SPELLCST_BLKG            = 7204;
const int FEAT_SAVANT_SPELLCST_SOL             = 7205;
const int FEAT_SAVANT_SPELLCST_VASSAL          = 7206;
const int FEAT_SAVANT_SPELLCST_KMC             = 7207;
const int FEAT_SAVANT_SPELLCST_KCH             = 7208;
const int FEAT_SAVANT_SPELLCST_APAL            = 7209;
const int FEAT_SAVANT_SPELLCST_VGL             = 7210;
const int FEAT_SAVANT_SPELLCST_FVS             = 7211;
const int FEAT_SAVANT_SPELLCST_SOHEI           = 7212;
const int FEAT_SAVANT_SPELLCST_HLR             = 7213;
const int FEAT_SAVANT_SPELLCST_SOD             = 7214;
const int FEAT_SAVANT_SPELLCST_OCULAR          = 7215;
const int FEAT_DRSLYR_SPELLCST_WIZ             = 7216;
const int FEAT_DRSLYR_SPELLCST_SORC            = 7217;
const int FEAT_DRSLYR_SPELLCST_BARD            = 7218;
const int FEAT_DRSLYR_SPELLCST_ASSN            = 7219;
const int FEAT_DRSLYR_SPELLCST_SUEL            = 7220;
const int FEAT_DRSLYR_SPELLCST_SHDL            = 7221;
const int FEAT_DRSLYR_SPELLCST_HEXBLD          = 7222;
const int FEAT_DRSLYR_SPELLCST_DSKBLD          = 7223;
const int FEAT_ENLFST_SPELLCST_WIZ             = 7224;
const int FEAT_ENLFST_SPELLCST_SORC            = 7225;
const int FEAT_ENLFST_SPELLCST_BARD            = 7226;
const int FEAT_ENLFST_SPELLCST_ASSN            = 7227;
const int FEAT_ENLFST_SPELLCST_SUEL            = 7228;
const int FEAT_ENLFST_SPELLCST_SHDL            = 7229;
const int FEAT_ENLFST_SPELLCST_HEXBLD          = 7230;
const int FEAT_ENLFST_SPELLCST_DSKBLD          = 7231;
const int FEAT_FISTRA_SPELLCST_CLER            = 7232;
const int FEAT_FISTRA_SPELLCST_DRUID           = 7233;
const int FEAT_FISTRA_SPELLCST_PAL             = 7234;
const int FEAT_FISTRA_SPELLCST_RNG             = 7235;
const int FEAT_FISTRA_SPELLCST_BLKG            = 7236;
const int FEAT_FISTRA_SPELLCST_SOL             = 7237;
const int FEAT_FISTRA_SPELLCST_VASSAL          = 7238;
const int FEAT_FISTRA_SPELLCST_KMC             = 7239;
const int FEAT_FISTRA_SPELLCST_KCH             = 7240;
const int FEAT_FISTRA_SPELLCST_APAL            = 7241;
const int FEAT_FISTRA_SPELLCST_VGL             = 7242;
const int FEAT_FISTRA_SPELLCST_FVS             = 7243;
const int FEAT_FISTRA_SPELLCST_SOHEI           = 7244;
const int FEAT_FISTRA_SPELLCST_HLR             = 7245;
const int FEAT_FISTRA_SPELLCST_SOD             = 7246;
const int FEAT_FISTRA_SPELLCST_OCULAR          = 7247;
const int FEAT_HMAGE_SPELLCST_WIZ              = 7248;
const int FEAT_HMAGE_SPELLCST_SORC             = 7249;
const int FEAT_HMAGE_SPELLCST_BARD             = 7250;
const int FEAT_HMAGE_SPELLCST_ASSN             = 7251;
const int FEAT_HMAGE_SPELLCST_SUEL             = 7252;
const int FEAT_HMAGE_SPELLCST_SHDL             = 7253;
const int FEAT_HMAGE_SPELLCST_HEXBLD           = 7254;
const int FEAT_HMAGE_SPELLCST_DSKBLD           = 7255;
const int FEAT_HATH_SPELLCST_WIZ               = 7256;
const int FEAT_HATH_SPELLCST_SORC              = 7257;
const int FEAT_HATH_SPELLCST_BARD              = 7258;
const int FEAT_HATH_SPELLCST_ASSN              = 7259;
const int FEAT_HATH_SPELLCST_SUEL              = 7260;
const int FEAT_HATH_SPELLCST_SHDL              = 7261;
const int FEAT_HATH_SPELLCST_HEXBLD            = 7262;
const int FEAT_HATH_SPELLCST_DSKBLD            = 7263;
const int FEAT_HATH_SPELLCST_CLER              = 7264;
const int FEAT_HATH_SPELLCST_DRUID             = 7265;
const int FEAT_HATH_SPELLCST_PAL               = 7266;
const int FEAT_HATH_SPELLCST_RNG               = 7267;
const int FEAT_HATH_SPELLCST_BLKG              = 7268;
const int FEAT_HATH_SPELLCST_SOL               = 7269;
const int FEAT_HATH_SPELLCST_VASSAL            = 7270;
const int FEAT_HATH_SPELLCST_KMC               = 7271;
const int FEAT_HATH_SPELLCST_KCH               = 7272;
const int FEAT_HATH_SPELLCST_APAL              = 7273;
const int FEAT_HATH_SPELLCST_VGL               = 7274;
const int FEAT_HATH_SPELLCST_FVS               = 7275;
const int FEAT_HATH_SPELLCST_SOHEI             = 7276;
const int FEAT_HATH_SPELLCST_HLR               = 7277;
const int FEAT_HATH_SPELLCST_SOD               = 7278;
const int FEAT_HATH_SPELLCST_OCULAR            = 7279;
const int FEAT_HAVOCM_SPELLCST_WIZ             = 7280;
const int FEAT_HAVOCM_SPELLCST_SORC            = 7281;
const int FEAT_HAVOCM_SPELLCST_BARD            = 7282;
const int FEAT_HAVOCM_SPELLCST_ASSN            = 7283;
const int FEAT_HAVOCM_SPELLCST_SUEL            = 7284;
const int FEAT_HAVOCM_SPELLCST_SHDL            = 7285;
const int FEAT_HAVOCM_SPELLCST_HEXBLD          = 7286;
const int FEAT_HAVOCM_SPELLCST_DSKBLD          = 7287;
const int FEAT_MAESTR_SPELLCST_WIZ             = 7288;
const int FEAT_MAESTR_SPELLCST_SORC            = 7289;
const int FEAT_MAESTR_SPELLCST_BARD            = 7290;
const int FEAT_MAESTR_SPELLCST_ASSN            = 7291;
const int FEAT_MAESTR_SPELLCST_SUEL            = 7292;
const int FEAT_MAESTR_SPELLCST_SHDL            = 7293;
const int FEAT_MAESTR_SPELLCST_HEXBLD          = 7294;
const int FEAT_MAESTR_SPELLCST_DSKBLD          = 7295;
const int FEAT_MAGEK_SPELLCST_WIZ              = 7296;
const int FEAT_MAGEK_SPELLCST_SORC             = 7297;
const int FEAT_MAGEK_SPELLCST_BARD             = 7298;
const int FEAT_MAGEK_SPELLCST_ASSN             = 7299;
const int FEAT_MAGEK_SPELLCST_SUEL             = 7300;
const int FEAT_MAGEK_SPELLCST_SHDL             = 7301;
const int FEAT_MAGEK_SPELLCST_HEXBLD           = 7302;
const int FEAT_MAGEK_SPELLCST_DSKBLD           = 7303;
const int FEAT_PALEMA_SPELLCST_WIZ             = 7304;
const int FEAT_PALEMA_SPELLCST_SORC            = 7305;
const int FEAT_PALEMA_SPELLCST_BARD            = 7306;
const int FEAT_PALEMA_SPELLCST_ASSN            = 7307;
const int FEAT_PALEMA_SPELLCST_SUEL            = 7308;
const int FEAT_PALEMA_SPELLCST_SHDL            = 7309;
const int FEAT_PALEMA_SPELLCST_HEXBLD          = 7310;
const int FEAT_PALEMA_SPELLCST_DSKBLD          = 7311;
const int FEAT_REDWIZ_SPELLCST_WIZ             = 7312;
const int FEAT_REDWIZ_SPELLCST_SORC            = 7313;
const int FEAT_REDWIZ_SPELLCST_BARD            = 7314;
const int FEAT_REDWIZ_SPELLCST_ASSN            = 7315;
const int FEAT_REDWIZ_SPELLCST_SUEL            = 7316;
const int FEAT_REDWIZ_SPELLCST_SHDL            = 7317;
const int FEAT_REDWIZ_SPELLCST_HEXBLD          = 7318;
const int FEAT_REDWIZ_SPELLCST_DSKBLD          = 7319;
const int FEAT_SPELLS_SPELLCST_WIZ             = 7320;
const int FEAT_SPELLS_SPELLCST_SORC            = 7321;
const int FEAT_SPELLS_SPELLCST_BARD            = 7322;
const int FEAT_SPELLS_SPELLCST_ASSN            = 7323;
const int FEAT_SPELLS_SPELLCST_SUEL            = 7324;
const int FEAT_SPELLS_SPELLCST_SHDL            = 7325;
const int FEAT_SPELLS_SPELLCST_HEXBLD          = 7326;
const int FEAT_SPELLS_SPELLCST_DSKBLD          = 7327;
const int FEAT_WWOC_SPELLCST_WIZ               = 7328;
const int FEAT_WWOC_SPELLCST_SORC              = 7329;
const int FEAT_WWOC_SPELLCST_BARD              = 7330;
const int FEAT_WWOC_SPELLCST_ASSN              = 7331;
const int FEAT_WWOC_SPELLCST_SUEL              = 7332;
const int FEAT_WWOC_SPELLCST_SHDL              = 7333;
const int FEAT_WWOC_SPELLCST_HEXBLD            = 7334;
const int FEAT_WWOC_SPELLCST_DSKBLD            = 7335;
const int FEAT_HEARTW_SPELLCST_CLER            = 7336;
const int FEAT_HEARTW_SPELLCST_DRUID           = 7337;
const int FEAT_HEARTW_SPELLCST_PAL             = 7338;
const int FEAT_HEARTW_SPELLCST_RNG             = 7339;
const int FEAT_HEARTW_SPELLCST_BLKG            = 7340;
const int FEAT_HEARTW_SPELLCST_SOL             = 7341;
const int FEAT_HEARTW_SPELLCST_VASSAL          = 7342;
const int FEAT_HEARTW_SPELLCST_KMC             = 7343;
const int FEAT_HEARTW_SPELLCST_KCH             = 7344;
const int FEAT_HEARTW_SPELLCST_APAL            = 7345;
const int FEAT_HEARTW_SPELLCST_VGL             = 7346;
const int FEAT_HEARTW_SPELLCST_FVS             = 7347;
const int FEAT_HEARTW_SPELLCST_SOHEI           = 7348;
const int FEAT_HEARTW_SPELLCST_HLR             = 7349;
const int FEAT_HEARTW_SPELLCST_SOD             = 7350;
const int FEAT_HEARTW_SPELLCST_OCULAR          = 7351;
const int FEAT_HOSP_SPELLCST_CLER              = 7352;
const int FEAT_HOSP_SPELLCST_DRUID             = 7353;
const int FEAT_HOSP_SPELLCST_PAL               = 7354;
const int FEAT_HOSP_SPELLCST_RNG               = 7355;
const int FEAT_HOSP_SPELLCST_BLKG              = 7356;
const int FEAT_HOSP_SPELLCST_SOL               = 7357;
const int FEAT_HOSP_SPELLCST_VASSAL            = 7358;
const int FEAT_HOSP_SPELLCST_KMC               = 7359;
const int FEAT_HOSP_SPELLCST_KCH               = 7360;
const int FEAT_HOSP_SPELLCST_APAL              = 7361;
const int FEAT_HOSP_SPELLCST_VGL               = 7362;
const int FEAT_HOSP_SPELLCST_FVS               = 7363;
const int FEAT_HOSP_SPELLCST_SOHEI             = 7364;
const int FEAT_HOSP_SPELLCST_HLR               = 7365;
const int FEAT_HOSP_SPELLCST_SOD               = 7366;
const int FEAT_HOSP_SPELLCST_OCULAR            = 7367;
const int FEAT_OLLAM_SPELLCST_CLER             = 7368;
const int FEAT_OLLAM_SPELLCST_DRUID            = 7369;
const int FEAT_OLLAM_SPELLCST_PAL              = 7370;
const int FEAT_OLLAM_SPELLCST_RNG              = 7371;
const int FEAT_OLLAM_SPELLCST_BLKG             = 7372;
const int FEAT_OLLAM_SPELLCST_SOL              = 7373;
const int FEAT_OLLAM_SPELLCST_VASSAL           = 7374;
const int FEAT_OLLAM_SPELLCST_KMC              = 7375;
const int FEAT_OLLAM_SPELLCST_KCH              = 7376;
const int FEAT_OLLAM_SPELLCST_APAL             = 7377;
const int FEAT_OLLAM_SPELLCST_VGL              = 7378;
const int FEAT_OLLAM_SPELLCST_FVS              = 7379;
const int FEAT_OLLAM_SPELLCST_SOHEI            = 7380;
const int FEAT_OLLAM_SPELLCST_HLR              = 7381;
const int FEAT_OLLAM_SPELLCST_SOD              = 7382;
const int FEAT_OLLAM_SPELLCST_OCULAR           = 7383;
const int FEAT_RUNEC_SPELLCST_CLER             = 7384;
const int FEAT_RUNEC_SPELLCST_DRUID            = 7385;
const int FEAT_RUNEC_SPELLCST_PAL              = 7386;
const int FEAT_RUNEC_SPELLCST_RNG              = 7387;
const int FEAT_RUNEC_SPELLCST_BLKG             = 7388;
const int FEAT_RUNEC_SPELLCST_SOL              = 7389;
const int FEAT_RUNEC_SPELLCST_VASSAL           = 7390;
const int FEAT_RUNEC_SPELLCST_KMC              = 7391;
const int FEAT_RUNEC_SPELLCST_KCH              = 7392;
const int FEAT_RUNEC_SPELLCST_APAL             = 7393;
const int FEAT_RUNEC_SPELLCST_VGL              = 7394;
const int FEAT_RUNEC_SPELLCST_FVS              = 7395;
const int FEAT_RUNEC_SPELLCST_SOHEI            = 7396;
const int FEAT_RUNEC_SPELLCST_HLR              = 7397;
const int FEAT_RUNEC_SPELLCST_SOD              = 7398;
const int FEAT_RUNEC_SPELLCST_OCULAR           = 7399;
const int FEAT_SACFIS_SPELLCST_CLER            = 7400;
const int FEAT_SACFIS_SPELLCST_DRUID           = 7401;
const int FEAT_SACFIS_SPELLCST_PAL             = 7402;
const int FEAT_SACFIS_SPELLCST_RNG             = 7403;
const int FEAT_SACFIS_SPELLCST_BLKG            = 7404;
const int FEAT_SACFIS_SPELLCST_SOL             = 7405;
const int FEAT_SACFIS_SPELLCST_VASSAL          = 7406;
const int FEAT_SACFIS_SPELLCST_KMC             = 7407;
const int FEAT_SACFIS_SPELLCST_KCH             = 7408;
const int FEAT_SACFIS_SPELLCST_APAL            = 7409;
const int FEAT_SACFIS_SPELLCST_VGL             = 7410;
const int FEAT_SACFIS_SPELLCST_FVS             = 7411;
const int FEAT_SACFIS_SPELLCST_SOHEI           = 7412;
const int FEAT_SACFIS_SPELLCST_HLR             = 7413;
const int FEAT_SACFIS_SPELLCST_SOD             = 7414;
const int FEAT_SACFIS_SPELLCST_OCULAR          = 7415;
const int FEAT_SBHEIR_SPELLCST_CLER            = 7416;
const int FEAT_SBHEIR_SPELLCST_DRUID           = 7417;
const int FEAT_SBHEIR_SPELLCST_PAL             = 7418;
const int FEAT_SBHEIR_SPELLCST_RNG             = 7419;
const int FEAT_SBHEIR_SPELLCST_BLKG            = 7420;
const int FEAT_SBHEIR_SPELLCST_SOL             = 7421;
const int FEAT_SBHEIR_SPELLCST_VASSAL          = 7422;
const int FEAT_SBHEIR_SPELLCST_KMC             = 7423;
const int FEAT_SBHEIR_SPELLCST_KCH             = 7424;
const int FEAT_SBHEIR_SPELLCST_APAL            = 7425;
const int FEAT_SBHEIR_SPELLCST_VGL             = 7426;
const int FEAT_SBHEIR_SPELLCST_FVS             = 7427;
const int FEAT_SBHEIR_SPELLCST_SOHEI           = 7428;
const int FEAT_SBHEIR_SPELLCST_HLR             = 7429;
const int FEAT_SBHEIR_SPELLCST_SOD             = 7430;
const int FEAT_SBHEIR_SPELLCST_OCULAR          = 7431;
const int FEAT_STORML_SPELLCST_CLER            = 7432;
const int FEAT_STORML_SPELLCST_DRUID           = 7433;
const int FEAT_STORML_SPELLCST_PAL             = 7434;
const int FEAT_STORML_SPELLCST_RNG             = 7435;
const int FEAT_STORML_SPELLCST_BLKG            = 7436;
const int FEAT_STORML_SPELLCST_SOL             = 7437;
const int FEAT_STORML_SPELLCST_VASSAL          = 7438;
const int FEAT_STORML_SPELLCST_KMC             = 7439;
const int FEAT_STORML_SPELLCST_KCH             = 7440;
const int FEAT_STORML_SPELLCST_APAL            = 7441;
const int FEAT_STORML_SPELLCST_VGL             = 7442;
const int FEAT_STORML_SPELLCST_FVS             = 7443;
const int FEAT_STORML_SPELLCST_SOHEI           = 7444;
const int FEAT_STORML_SPELLCST_HLR             = 7445;
const int FEAT_STORML_SPELLCST_SOD             = 7446;
const int FEAT_STORML_SPELLCST_OCULAR          = 7447;
const int FEAT_BLTL_SPELLCST_CLER              = 7448;
const int FEAT_BLTL_SPELLCST_DRUID             = 7449;
const int FEAT_BLTL_SPELLCST_PAL               = 7450;
const int FEAT_BLTL_SPELLCST_RNG               = 7451;
const int FEAT_BLTL_SPELLCST_BLKG              = 7452;
const int FEAT_BLTL_SPELLCST_SOL               = 7453;
const int FEAT_BLTL_SPELLCST_VASSAL            = 7454;
const int FEAT_BLTL_SPELLCST_KMC               = 7455;
const int FEAT_BLTL_SPELLCST_KCH               = 7456;
const int FEAT_BLTL_SPELLCST_APAL              = 7457;
const int FEAT_BLTL_SPELLCST_VGL               = 7458;
const int FEAT_BLTL_SPELLCST_FVS               = 7459;
const int FEAT_BLTL_SPELLCST_SOHEI             = 7460;
const int FEAT_BLTL_SPELLCST_HLR               = 7461;
const int FEAT_BLTL_SPELLCST_SOD               = 7462;
const int FEAT_BLTL_SPELLCST_OCULAR            = 7463;
const int FEAT_ORCUS_SPELLCST_CLER             = 7464;
const int FEAT_ORCUS_SPELLCST_DRUID            = 7465;
const int FEAT_ORCUS_SPELLCST_PAL              = 7466;
const int FEAT_ORCUS_SPELLCST_RNG              = 7467;
const int FEAT_ORCUS_SPELLCST_BLKG             = 7468;
const int FEAT_ORCUS_SPELLCST_SOL              = 7469;
const int FEAT_ORCUS_SPELLCST_VASSAL           = 7470;
const int FEAT_ORCUS_SPELLCST_KMC              = 7471;
const int FEAT_ORCUS_SPELLCST_KCH              = 7472;
const int FEAT_ORCUS_SPELLCST_APAL             = 7473;
const int FEAT_ORCUS_SPELLCST_VGL              = 7474;
const int FEAT_ORCUS_SPELLCST_FVS              = 7475;
const int FEAT_ORCUS_SPELLCST_SOHEI            = 7476;
const int FEAT_ORCUS_SPELLCST_HLR              = 7477;
const int FEAT_ORCUS_SPELLCST_SOD              = 7478;
const int FEAT_ORCUS_SPELLCST_OCULAR           = 7479;
const int FEAT_WARPR_SPELLCST_CLER             = 7480;
const int FEAT_WARPR_SPELLCST_DRUID            = 7481;
const int FEAT_WARPR_SPELLCST_PAL              = 7482;
const int FEAT_WARPR_SPELLCST_RNG              = 7483;
const int FEAT_WARPR_SPELLCST_BLKG             = 7484;
const int FEAT_WARPR_SPELLCST_SOL              = 7485;
const int FEAT_WARPR_SPELLCST_VASSAL           = 7486;
const int FEAT_WARPR_SPELLCST_KMC              = 7487;
const int FEAT_WARPR_SPELLCST_KCH              = 7488;
const int FEAT_WARPR_SPELLCST_APAL             = 7489;
const int FEAT_WARPR_SPELLCST_VGL              = 7490;
const int FEAT_WARPR_SPELLCST_FVS              = 7491;
const int FEAT_WARPR_SPELLCST_SOHEI            = 7492;
const int FEAT_WARPR_SPELLCST_HLR              = 7493;
const int FEAT_WARPR_SPELLCST_SOD              = 7494;
const int FEAT_WARPR_SPELLCST_OCULAR           = 7495;
const int FEAT_MOS_SPELLCST_CLER               = 7496;
const int FEAT_MYSTIC_SPELLCST_WIZ             = 7497;
const int FEAT_MYSTIC_SPELLCST_SORC            = 7498;
const int FEAT_MYSTIC_SPELLCST_BARD            = 7499;
const int FEAT_MYSTIC_SPELLCST_ASSN            = 7500;
const int FEAT_MYSTIC_SPELLCST_SUEL            = 7501;
const int FEAT_MYSTIC_SPELLCST_SHDL            = 7502;
const int FEAT_MYSTIC_SPELLCST_HEXBLD          = 7503;
const int FEAT_MYSTIC_SPELLCST_DSKBLD          = 7504;
const int FEAT_MYSTIC_SPELLCST_CLER            = 7505;
const int FEAT_MYSTIC_SPELLCST_DRUID           = 7506;
const int FEAT_MYSTIC_SPELLCST_PAL             = 7507;
const int FEAT_MYSTIC_SPELLCST_RNG             = 7508;
const int FEAT_MYSTIC_SPELLCST_BLKG            = 7509;
const int FEAT_MYSTIC_SPELLCST_SOL             = 7510;
const int FEAT_MYSTIC_SPELLCST_VASSAL          = 7511;
const int FEAT_MYSTIC_SPELLCST_KMC             = 7512;
const int FEAT_MYSTIC_SPELLCST_KCH             = 7513;
const int FEAT_MYSTIC_SPELLCST_APAL            = 7514;
const int FEAT_MYSTIC_SPELLCST_VGL             = 7515;
const int FEAT_MYSTIC_SPELLCST_FVS             = 7516;
const int FEAT_MYSTIC_SPELLCST_SOHEI           = 7517;
const int FEAT_MYSTIC_SPELLCST_HLR             = 7518;
const int FEAT_MYSTIC_SPELLCST_SOD             = 7519;
const int FEAT_MYSTIC_SPELLCST_OCULAR          = 7520;
const int FEAT_OOZE_SPELLCST_WIZ               = 7521;
const int FEAT_OOZE_SPELLCST_SORC              = 7522;
const int FEAT_OOZE_SPELLCST_BARD              = 7523;
const int FEAT_OOZE_SPELLCST_ASSN              = 7524;
const int FEAT_OOZE_SPELLCST_SUEL              = 7525;
const int FEAT_OOZE_SPELLCST_SHDL              = 7526;
const int FEAT_OOZE_SPELLCST_HEXBLD            = 7527;
const int FEAT_OOZE_SPELLCST_DSKBLD            = 7528;
const int FEAT_OOZE_SPELLCST_CLER              = 7529;
const int FEAT_OOZE_SPELLCST_DRUID             = 7530;
const int FEAT_OOZE_SPELLCST_PAL               = 7531;
const int FEAT_OOZE_SPELLCST_RNG               = 7532;
const int FEAT_OOZE_SPELLCST_BLKG              = 7533;
const int FEAT_OOZE_SPELLCST_SOL               = 7534;
const int FEAT_OOZE_SPELLCST_VASSAL            = 7535;
const int FEAT_OOZE_SPELLCST_KMC               = 7536;
const int FEAT_OOZE_SPELLCST_KCH               = 7537;
const int FEAT_OOZE_SPELLCST_APAL              = 7538;
const int FEAT_OOZE_SPELLCST_VGL               = 7539;
const int FEAT_OOZE_SPELLCST_FVS               = 7540;
const int FEAT_OOZE_SPELLCST_SOHEI             = 7541;
const int FEAT_OOZE_SPELLCST_HLR               = 7542;
const int FEAT_OOZE_SPELLCST_SOD               = 7543;
const int FEAT_OOZE_SPELLCST_OCULAR            = 7544;
const int FEAT_SHADEPT_SPELLCST_WIZ            = 7545;
const int FEAT_SHADEPT_SPELLCST_SORC           = 7546;
const int FEAT_SHADEPT_SPELLCST_BARD           = 7547;
const int FEAT_SHADEPT_SPELLCST_ASSN           = 7548;
const int FEAT_SHADEPT_SPELLCST_SUEL           = 7549;
const int FEAT_SHADEPT_SPELLCST_SHDL           = 7550;
const int FEAT_SHADEPT_SPELLCST_HEXBLD         = 7551;
const int FEAT_SHADEPT_SPELLCST_DSKBLD         = 7552;
const int FEAT_SHADEPT_SPELLCST_CLER           = 7553;
const int FEAT_SHADEPT_SPELLCST_DRUID          = 7554;
const int FEAT_SHADEPT_SPELLCST_PAL            = 7555;
const int FEAT_SHADEPT_SPELLCST_RNG            = 7556;
const int FEAT_SHADEPT_SPELLCST_BLKG           = 7557;
const int FEAT_SHADEPT_SPELLCST_SOL            = 7558;
const int FEAT_SHADEPT_SPELLCST_VASSAL         = 7559;
const int FEAT_SHADEPT_SPELLCST_KMC            = 7560;
const int FEAT_SHADEPT_SPELLCST_KCH            = 7561;
const int FEAT_SHADEPT_SPELLCST_APAL           = 7562;
const int FEAT_SHADEPT_SPELLCST_VGL            = 7563;
const int FEAT_SHADEPT_SPELLCST_FVS            = 7564;
const int FEAT_SHADEPT_SPELLCST_SOHEI          = 7565;
const int FEAT_SHADEPT_SPELLCST_HLR            = 7566;
const int FEAT_SHADEPT_SPELLCST_SOD            = 7567;
const int FEAT_SHADEPT_SPELLCST_OCULAR         = 7568;
const int FEAT_TOG_SPELLCST_WIZ                = 7569;
const int FEAT_TOG_SPELLCST_SORC               = 7570;
const int FEAT_TOG_SPELLCST_BARD               = 7571;
const int FEAT_TOG_SPELLCST_ASSN               = 7572;
const int FEAT_TOG_SPELLCST_SUEL               = 7573;
const int FEAT_TOG_SPELLCST_SHDL               = 7574;
const int FEAT_TOG_SPELLCST_HEXBLD             = 7575;
const int FEAT_TOG_SPELLCST_DSKBLD             = 7576;
const int FEAT_TOG_SPELLCST_CLER               = 7577;
const int FEAT_TOG_SPELLCST_DRUID              = 7578;
const int FEAT_TOG_SPELLCST_PAL                = 7579;
const int FEAT_TOG_SPELLCST_RNG                = 7580;
const int FEAT_TOG_SPELLCST_BLKG               = 7581;
const int FEAT_TOG_SPELLCST_SOL                = 7582;
const int FEAT_TOG_SPELLCST_VASSAL             = 7583;
const int FEAT_TOG_SPELLCST_KMC                = 7584;
const int FEAT_TOG_SPELLCST_KCH                = 7585;
const int FEAT_TOG_SPELLCST_APAL               = 7586;
const int FEAT_TOG_SPELLCST_VGL                = 7587;
const int FEAT_TOG_SPELLCST_FVS                = 7588;
const int FEAT_TOG_SPELLCST_SOHEI              = 7589;
const int FEAT_TOG_SPELLCST_HLR                = 7590;
const int FEAT_TOG_SPELLCST_SOD                = 7591;
const int FEAT_TOG_SPELLCST_OCULAR             = 7592;
const int FEAT_TRUE_SPELLCST_WIZ               = 7593;
const int FEAT_TRUE_SPELLCST_SORC              = 7594;
const int FEAT_TRUE_SPELLCST_BARD              = 7595;
const int FEAT_TRUE_SPELLCST_ASSN              = 7596;
const int FEAT_TRUE_SPELLCST_SUEL              = 7597;
const int FEAT_TRUE_SPELLCST_SHDL              = 7598;
const int FEAT_TRUE_SPELLCST_HEXBLD            = 7599;
const int FEAT_TRUE_SPELLCST_DSKBLD            = 7600;
const int FEAT_TRUE_SPELLCST_CLER              = 7601;
const int FEAT_TRUE_SPELLCST_DRUID             = 7602;
const int FEAT_TRUE_SPELLCST_PAL               = 7603;
const int FEAT_TRUE_SPELLCST_RNG               = 7604;
const int FEAT_TRUE_SPELLCST_BLKG              = 7605;
const int FEAT_TRUE_SPELLCST_SOL               = 7606;
const int FEAT_TRUE_SPELLCST_VASSAL            = 7607;
const int FEAT_TRUE_SPELLCST_KMC               = 7608;
const int FEAT_TRUE_SPELLCST_KCH               = 7609;
const int FEAT_TRUE_SPELLCST_APAL              = 7610;
const int FEAT_TRUE_SPELLCST_VGL               = 7611;
const int FEAT_TRUE_SPELLCST_FVS               = 7612;
const int FEAT_TRUE_SPELLCST_SOHEI             = 7613;
const int FEAT_TRUE_SPELLCST_HLR               = 7614;
const int FEAT_TRUE_SPELLCST_SOD               = 7615;
const int FEAT_TRUE_SPELLCST_OCULAR            = 7616;
const int FEAT_PSYCH_SPELLCST_CLER             = 7617;
const int FEAT_PSYCH_SPELLCST_DRUID            = 7618;
const int FEAT_PSYCH_SPELLCST_PAL              = 7619;
const int FEAT_PSYCH_SPELLCST_RNG              = 7620;
const int FEAT_PSYCH_SPELLCST_BLKG             = 7621;
const int FEAT_PSYCH_SPELLCST_SOL              = 7622;
const int FEAT_PSYCH_SPELLCST_VASSAL           = 7623;
const int FEAT_PSYCH_SPELLCST_KMC              = 7624;
const int FEAT_PSYCH_SPELLCST_KCH              = 7625;
const int FEAT_PSYCH_SPELLCST_APAL             = 7626;
const int FEAT_PSYCH_SPELLCST_VGL              = 7627;
const int FEAT_PSYCH_SPELLCST_FVS              = 7628;
const int FEAT_PSYCH_SPELLCST_SOHEI            = 7629;
const int FEAT_PSYCH_SPELLCST_HLR              = 7630;
const int FEAT_PSYCH_SPELLCST_SOD              = 7631;
const int FEAT_PSYCH_SPELLCST_OCULAR           = 7632;
const int FEAT_PSYCH_SPELLCST_PSION            = 7633;
const int FEAT_PSYCH_SPELLCST_PSYCH            = 7634;
const int FEAT_PSYCH_SPELLCST_WILDER           = 7635;
const int FEAT_PSYCH_SPELLCST_WARMIND          = 7636;
const int FEAT_PSYCH_SPELLCST_FISTZ            = 7637;
const int FEAT_SNCMND_SPELLCST_CLER            = 7638;
const int FEAT_SNCMND_SPELLCST_DRUID           = 7639;
const int FEAT_SNCMND_SPELLCST_PAL             = 7640;
const int FEAT_SNCMND_SPELLCST_RNG             = 7641;
const int FEAT_SNCMND_SPELLCST_BLKG            = 7642;
const int FEAT_SNCMND_SPELLCST_SOL             = 7643;
const int FEAT_SNCMND_SPELLCST_VASSAL          = 7644;
const int FEAT_SNCMND_SPELLCST_KMC             = 7645;
const int FEAT_SNCMND_SPELLCST_KCH             = 7646;
const int FEAT_SNCMND_SPELLCST_APAL            = 7647;
const int FEAT_SNCMND_SPELLCST_VGL             = 7648;
const int FEAT_SNCMND_SPELLCST_FVS             = 7649;
const int FEAT_SNCMND_SPELLCST_SOHEI           = 7650;
const int FEAT_SNCMND_SPELLCST_HLR             = 7651;
const int FEAT_SNCMND_SPELLCST_SOD             = 7652;
const int FEAT_SNCMND_SPELLCST_OCULAR          = 7653;
const int FEAT_SNCMND_SPELLCST_PSION           = 7654;
const int FEAT_SNCMND_SPELLCST_PSYCH           = 7655;
const int FEAT_SNCMND_SPELLCST_WILDER          = 7656;
const int FEAT_SNCMND_SPELLCST_WARMIND         = 7657;
const int FEAT_SNCMND_SPELLCST_FISTZ           = 7658;
const int FEAT_ORCUS_SPELLCST_WIZ              = 7659;
const int FEAT_ORCUS_SPELLCST_SORC             = 7660;
const int FEAT_ORCUS_SPELLCST_BARD             = 7661;
const int FEAT_ORCUS_SPELLCST_ASSN             = 7662;
const int FEAT_ORCUS_SPELLCST_SUEL             = 7663;
const int FEAT_ORCUS_SPELLCST_SHDL             = 7664;
const int FEAT_ORCUS_SPELLCST_HEXBLD           = 7665;
const int FEAT_ORCUS_SPELLCST_DSKBLD           = 7666;
const int FEAT_EK_SPELLCST_WIZ                 = 7667;
const int FEAT_EK_SPELLCST_SORC                = 7668;
const int FEAT_EK_SPELLCST_BARD                = 7669;
const int FEAT_EK_SPELLCST_ASSN                = 7670;
const int FEAT_EK_SPELLCST_SUEL                = 7671;
const int FEAT_EK_SPELLCST_SHDL                = 7672;
const int FEAT_EK_SPELLCST_HEXBLD              = 7673;
const int FEAT_EK_SPELLCST_DSKBLD              = 7674;

// Dragon Shaman
const int FEAT_DRAGONSHAMAN_RESOLVE               = 3838;
const int FEAT_DRAGONSHAMAN_TOUCHVITALITY         = 3834;
const int FEAT_DRAGONSHAMAN_TOUCHVITALITY_MINOR   = 3835;
const int FEAT_DRAGONSHAMAN_TOUCHVITALITY_RESTORE = 3836;
const int FEAT_DRAGONSHAMAN_TOUCHVITALITY_MAJOR   = 3837;
const int FEAT_DRAGONSHAMAN_BREATH                = 3840;
const int FEAT_DRAGONSHAMAN_AURA_POWER            = 3826;
const int FEAT_DRAGONSHAMAN_AURA_SENSES           = 3829;
const int FEAT_DRAGONSHAMAN_AURA_PRESENCE         = 3832;
const int FEAT_DRAGONSHAMAN_AURA_RESISTANCE       = 3831;
const int FEAT_DRAGONSHAMAN_AURA_ENERGYSHLD       = 3827;
const int FEAT_DRAGONSHAMAN_AURA_VIGOR            = 3830;
const int FEAT_DRAGONSHAMAN_AURA_TOUGHNESS        = 3828;
const int FEAT_DRAGONSHAMAN_ARMOR                 = 3833;
const int FEAT_DRAGONSHAMAN_ENERGY_IMMUNITY       = 3839;
const int FEAT_DRAGONSHAMAN_RED                   = 3841;
const int FEAT_DRAGONSHAMAN_BLACK                 = 3844;
const int FEAT_DRAGONSHAMAN_BLUE                  = 3842;
const int FEAT_DRAGONSHAMAN_SILVER                = 3846;
const int FEAT_DRAGONSHAMAN_BRASS                 = 3848;
const int FEAT_DRAGONSHAMAN_GOLD                  = 3847;
const int FEAT_DRAGONSHAMAN_GREEN                 = 3843;
const int FEAT_DRAGONSHAMAN_COPPER                = 3850;
const int FEAT_DRAGONSHAMAN_WHITE                 = 3845;
const int FEAT_DRAGONSHAMAN_BRONZE                = 3849;

// Shaman
const int FEAT_SHAMAN_SPIRITFAVOR                       = 3851;
const int FEAT_SHAMAN_PRACTICEDCASTER                   = 3852;
const int FEAT_EXTRA_SLOT_SHAMAN_0                      = 3853;
const int FEAT_EXTRA_SLOT_SHAMAN_1                      = 3854;
const int FEAT_EXTRA_SLOT_SHAMAN_2                      = 3855;
const int FEAT_EXTRA_SLOT_SHAMAN_3                      = 3856;
const int FEAT_EXTRA_SLOT_SHAMAN_4                      = 3857;
const int FEAT_EXTRA_SLOT_SHAMAN_5                      = 3858;
const int FEAT_EXTRA_SLOT_SHAMAN_6                      = 3859;
const int FEAT_EXTRA_SLOT_SHAMAN_7                      = 3860;
const int FEAT_EXTRA_SLOT_SHAMAN_8                      = 3861;


/*//////////////////////////////////////////////////
//////////////// TRUENAMING ////////////////////////
//////////////////////////////////////////////////*/

// General Feats
const int FEAT_TRUENAME_TRAINING                        = 6275;
const int FEAT_SKILL_FOCUS_TRUESPEAK                    = 6282;
const int FEAT_EPIC_SKILL_FOCUS_TRUESPEAK               = 6283;

// Metautterance feats
const int FEAT_EMPOWER_UTTERANCE                        = 6272;
const int FEAT_EXTEND_UTTERANCE                         = 6273;
const int FEAT_QUICKEN_UTTERANCE                        = 6274;

// Recitation feats
const int FEAT_RECITATION_FORTIFIED                     = 6267;
const int FEAT_RECITATION_MEDITATIVE                    = 6268;
const int FEAT_RECITATION_MINDFUL                       = 6269;
const int FEAT_RECITATION_SANGUINE                      = 6270;
const int FEAT_RECITATION_VITAL                         = 6271;

// Utterance Focus
const int FEAT_UTTERANCE_FOCUS_BREATH_CLEANSING         = 6255;
const int FEAT_UTTERANCE_FOCUS_BREATH_RECOVERY          = 6256;
const int FEAT_UTTERANCE_FOCUS_ELDRITCH_ATTRACTION      = 6257;
const int FEAT_UTTERANCE_FOCUS_MORALE_BOOST             = 6258;
const int FEAT_UTTERANCE_FOCUS_PRETERNATURAL_CLARITY    = 6259;
const int FEAT_UTTERANCE_FOCUS_SENSORY_FOCUS            = 6260;
const int FEAT_UTTERANCE_FOCUS_SILENT_CASTER            = 6261;
const int FEAT_UTTERANCE_FOCUS_SINGULAR_MIND            = 6262;
const int FEAT_UTTERANCE_FOCUS_TEMPORAL_SPIRAL          = 6263;
const int FEAT_UTTERANCE_FOCUS_TEMPORAL_TWIST           = 6264;
const int FEAT_UTTERANCE_FOCUS_WARD_PEACE               = 6265;
const int FEAT_UTTERANCE_FOCUS_SHOCKWAVE                = 6266;

// Focused Lexicon
const int FEAT_FOCUSED_LEXICON_ABERRATION               = 6230;
const int FEAT_FOCUSED_LEXICON_ANIMAL                   = 6231;
const int FEAT_FOCUSED_LEXICON_BEAST                    = 6232;
const int FEAT_FOCUSED_LEXICON_CONSTRUCT                = 6233;
const int FEAT_FOCUSED_LEXICON_DRAGON                   = 6234;
const int FEAT_FOCUSED_LEXICON_DWARF                    = 6235;
const int FEAT_FOCUSED_LEXICON_ELEMENTAL                = 6236;
const int FEAT_FOCUSED_LEXICON_ELF                      = 6237;
const int FEAT_FOCUSED_LEXICON_FEY                      = 6238;
const int FEAT_FOCUSED_LEXICON_GIANT                    = 6239;
const int FEAT_FOCUSED_LEXICON_GNOME                    = 6240;
const int FEAT_FOCUSED_LEXICON_HALFELF                  = 6241;
const int FEAT_FOCUSED_LEXICON_HALFLING                 = 6242;
const int FEAT_FOCUSED_LEXICON_HALFORC                  = 6243;
const int FEAT_FOCUSED_LEXICON_HUMAN                    = 6244;
const int FEAT_FOCUSED_LEXICON_GOBLINOID                = 6245;
const int FEAT_FOCUSED_LEXICON_MONSTROUS                = 6246;
const int FEAT_FOCUSED_LEXICON_ORC                      = 6247;
const int FEAT_FOCUSED_LEXICON_REPTILIAN                = 6248;
const int FEAT_FOCUSED_LEXICON_MAGICALBEAST             = 6249;
const int FEAT_FOCUSED_LEXICON_OOZE                     = 6250;
const int FEAT_FOCUSED_LEXICON_OUTSIDER                 = 6251;
const int FEAT_FOCUSED_LEXICON_SHAPECHANGER             = 6252;
const int FEAT_FOCUSED_LEXICON_UNDEAD                   = 6253;
const int FEAT_FOCUSED_LEXICON_VERMIN                   = 6254;

/*//////////////////////////////////////////////////
//////////////// END TRUENAMING/////////////////////
//////////////////////////////////////////////////*/

/*//////////////////////////////////////////////////
//////////////// BEGIN TOME OF BATTLE///////////////
//////////////////////////////////////////////////*/

const int FEAT_EXTRA_GRANTED_MANEUVER                   = 4096;
const int FEAT_EXTRA_READIED_MANEUVER                   = 4097;
const int FEAT_ADAPTIVE_STYLE                           = 4098;
const int FEAT_BLADE_MEDITATION                         = 4099;
const int FEAT_DESERT_FIRE                              = 4178;
const int FEAT_DESERT_WIND_DODGE                        = 4179;
const int FEAT_DEVOTED_BULWARK                          = 4180;
const int FEAT_AVENGING_STRIKE                          = 4297;
const int FEAT_RAPID_ASSAULT                            = 4299;
const int FEAT_SUPERIOR_UNARMED_STRIKE                  = 4386;
const int FEAT_SNAP_KICK                                = 4398;
const int FEAT_WEAPON_FOCUS_APTITUDE                    = 2123;
const int FEAT_EPIC_WEAPON_FOCUS_APTITUDE               = 2124;
const int FEAT_WEAPON_SPECIALIZATION_APTITUDE           = 2125;
const int FEAT_EPIC_WEAPON_SPECIALIZATION_APTITUDE      = 2126;
const int FEAT_IMPROVED_CRITICAL_APTITUDE               = 2127;
const int FEAT_SANCTIFY_MARTIAL_APTITUDE                = 2128;
const int FEAT_VILE_MARTIAL_APTITUDE                    = 2129;

const int FEAT_SS_DF_IS_DW                  = 2201;
const int FEAT_SS_DF_IS_DM                  = 2202;
const int FEAT_SS_DF_IS_SS                  = 2203;
const int FEAT_SS_DF_IS_SH                  = 2204;
const int FEAT_SS_DF_IS_SD                  = 2205;
const int FEAT_SS_DF_IS_TC                  = 2206;

const int FEAT_SS_DF_DS_DW                  = 2201;
const int FEAT_SS_DF_DS_DM                  = 2202;
const int FEAT_SS_DF_DS_SS                  = 2203;
const int FEAT_SS_DF_DS_SH                  = 2204;
const int FEAT_SS_DF_DS_SD                  = 2205;
const int FEAT_SS_DF_DS_TC                  = 2206;

const int FEAT_SS_DF_WF_DW                  = 2195;
const int FEAT_SS_DF_WF_DM                  = 2196;
const int FEAT_SS_DF_WF_SS                  = 2197;
const int FEAT_SS_DF_WF_SH                  = 2198;
const int FEAT_SS_DF_WF_SD                  = 2199;
const int FEAT_SS_DF_WF_TC                  = 2200;

/*//////////////////////////////////////////////////
//////////////// END TOME OF BATTLE/////////////////
//////////////////////////////////////////////////*/